use cardshumanity;
/*delete from cartablanca where emailUsuario = "default" and nombreBaraja = "Default Deck Eng";
delete from cartanegra where emailUsuario = "default" and nombreBaraja = "Default Deck Eng";
delete from carta where emailUsuario = "default" and nombreBaraja = "Default Deck Eng";
delete from baraja where emailUsuario = "default" and nombreBaraja = "Default Deck Eng";
*/

insert into Baraja values('default', 'Default Deck Eng', 'en');
insert into cartablanca values(0, 'default', 'Default Deck Eng', "Being on fire.");
insert into cartablanca values(1, 'default', 'Default Deck Eng', "Racism.");
insert into cartablanca values(2, 'default', 'Default Deck Eng', "Old-people smell.");
insert into cartablanca values(3, 'default', 'Default Deck Eng', "A micropenis.");
insert into cartablanca values(4, 'default', 'Default Deck Eng', "Women in yogurt commercials.");
insert into cartablanca values(5, 'default', 'Default Deck Eng', "Classist undertones.");
insert into cartablanca values(6, 'default', 'Default Deck Eng', "Not giving a shit about the Third World.");
insert into cartablanca values(7, 'default', 'Default Deck Eng', "Inserting a mason jar into my anus.");
insert into cartablanca values(8, 'default', 'Default Deck Eng', "Court-ordered rehab.");
insert into cartablanca values(9, 'default', 'Default Deck Eng', "A windmill full of corpses.");
insert into cartablanca values(10, 'default', 'Default Deck Eng', "The gays.");
insert into cartablanca values(11, 'default', 'Default Deck Eng', "An oversized lollipop.");
insert into cartablanca values(12, 'default', 'Default Deck Eng', "African children.");
insert into cartablanca values(13, 'default', 'Default Deck Eng', "An asymmetric boob job.");
insert into cartablanca values(14, 'default', 'Default Deck Eng', "Bingeing and purging.");
insert into cartablanca values(15, 'default', 'Default Deck Eng', "The hardworking Mexican.");
insert into cartablanca values(16, 'default', 'Default Deck Eng', "An Oedipus complex.");
insert into cartablanca values(17, 'default', 'Default Deck Eng', "A tiny horse.");
insert into cartablanca values(18, 'default', 'Default Deck Eng', "Boogers.");
insert into cartablanca values(19, 'default', 'Default Deck Eng', "Penis envy.");
insert into cartablanca values(20, 'default', 'Default Deck Eng', "Barack Obama.");
insert into cartablanca values(21, 'default', 'Default Deck Eng', "My humps.");
insert into cartablanca values(22, 'default', 'Default Deck Eng', "The TempurPedic Swedish Sleep System.");
insert into cartablanca values(23, 'default', 'Default Deck Eng', "Scientology.");
insert into cartablanca values(24, 'default', 'Default Deck Eng', "Dry heaving.");
insert into cartablanca values(25, 'default', 'Default Deck Eng', "Skeletor.");
insert into cartablanca values(26, 'default', 'Default Deck Eng', "Darth Vader.");
insert into cartablanca values(27, 'default', 'Default Deck Eng', "Figgy pudding.");
insert into cartablanca values(28, 'default', 'Default Deck Eng', "Advice from a wise, old black man.");
insert into cartablanca values(29, 'default', 'Default Deck Eng', "Five-Dollar Foo?ongs.");
insert into cartablanca values(30, 'default', 'Default Deck Eng', "Elderly Japanese men.");
insert into cartablanca values(31, 'default', 'Default Deck Eng', "Free samples.");
insert into cartablanca values(32, 'default', 'Default Deck Eng', "Estrogen.");
insert into cartablanca values(33, 'default', 'Default Deck Eng', "Sexual tension.");
insert into cartablanca values(34, 'default', 'Default Deck Eng', "Famine.");
insert into cartablanca values(35, 'default', 'Default Deck Eng', "A stray pube.");
insert into cartablanca values(36, 'default', 'Default Deck Eng', "Men.");
insert into cartablanca values(37, 'default', 'Default Deck Eng', "Heartwarming orphans.");
insert into cartablanca values(38, 'default', 'Default Deck Eng', "Chunks of dead hitchhiker.");
insert into cartablanca values(39, 'default', 'Default Deck Eng', "A bag of magic beans.");
insert into cartablanca values(40, 'default', 'Default Deck Eng', "Repression.");
insert into cartablanca values(41, 'default', 'Default Deck Eng', "Prancing.");
insert into cartablanca values(42, 'default', 'Default Deck Eng', "My relationship status.");
insert into cartablanca values(43, 'default', 'Default Deck Eng', "Overcompensation");
insert into cartablanca values(44, 'default', 'Default Deck Eng', "Peeing a little bit.");
insert into cartablanca values(45, 'default', 'Default Deck Eng', "Pooping back and forth forever.");
insert into cartablanca values(46, 'default', 'Default Deck Eng', "A ball of earwax,semen, and toenail clippings.");
insert into cartablanca values(47, 'default', 'Default Deck Eng', "Testicular torsion.");
insert into cartablanca values(48, 'default', 'Default Deck Eng', "The Devil himself.");
insert into cartablanca values(49, 'default', 'Default Deck Eng', "The World of Warcraft.");
insert into cartablanca values(50, 'default', 'Default Deck Eng', "Dick Cheney.");
insert into cartablanca values(51, 'default', 'Default Deck Eng', "MechaHitler.");
insert into cartablanca values(52, 'default', 'Default Deck Eng', "Being fabulous.");
insert into cartablanca values(53, 'default', 'Default Deck Eng', "Pictures of boobs.");
insert into cartablanca values(54, 'default', 'Default Deck Eng', "A gentle caress of the inner thigh.");
insert into cartablanca values(55, 'default', 'Default Deck Eng', "The Amish.");
insert into cartablanca values(56, 'default', 'Default Deck Eng', "The rhythms of Africa.");
insert into cartablanca values(57, 'default', 'Default Deck Eng', "Lance Armstrong's missing testicle.");
insert into cartablanca values(58, 'default', 'Default Deck Eng', "Pedophiles.");
insert into cartablanca values(59, 'default', 'Default Deck Eng', "The Pope.");
insert into cartablanca values(60, 'default', 'Default Deck Eng', "Flying sex snakes.");
insert into cartablanca values(61, 'default', 'Default Deck Eng', "Sarah PaIin .");
insert into cartablanca values(62, 'default', 'Default Deck Eng', "Feeding Rosie O'Donnell.");
insert into cartablanca values(63, 'default', 'Default Deck Eng', "Sexy pillow fights.");
insert into cartablanca values(64, 'default', 'Default Deck Eng', "lnvading Poland.");
insert into cartablanca values(65, 'default', 'Default Deck Eng', "Cybernetic enhancements.");
insert into cartablanca values(66, 'default', 'Default Deck Eng', "Civilian casualties.");
insert into cartablanca values(67, 'default', 'Default Deck Eng', "Jobs.");
insert into cartablanca values(68, 'default', 'Default Deck Eng', "The female orgasm.");
insert into cartablanca values(69, 'default', 'Default Deck Eng', "Bitches.");
insert into cartablanca values(70, 'default', 'Default Deck Eng', "The Boy Scouts of America.");
insert into cartablanca values(71, 'default', 'Default Deck Eng', "Auschwitz.");
insert into cartablanca values(72, 'default', 'Default Deck Eng', "Finger painting.");
insert into cartablanca values(73, 'default', 'Default Deck Eng', "The Care Bear Stare.");
insert into cartablanca values(74, 'default', 'Default Deck Eng', "The Jews.");
insert into cartablanca values(75, 'default', 'Default Deck Eng', "Being marginalized");
insert into cartablanca values(76, 'default', 'Default Deck Eng', "The Blood of Christ.");
insert into cartablanca values(77, 'default', 'Default Deck Eng', "Dead parents.");
insert into cartablanca values(78, 'default', 'Default Deck Eng', "The art of seduction.");
insert into cartablanca values(79, 'default', 'Default Deck Eng', "Dying of dysentery.");
insert into cartablanca values(80, 'default', 'Default Deck Eng', "Mr. Clean, right behind you.");
insert into cartablanca values(81, 'default', 'Default Deck Eng', "Magnets.");
insert into cartablanca values(82, 'default', 'Default Deck Eng', "Jewish fraternities.");
insert into cartablanca values(83, 'default', 'Default Deck Eng', "Hot Pockets.");
insert into cartablanca values(84, 'default', 'Default Deck Eng', "Natalie Portman.");
insert into cartablanca values(85, 'default', 'Default Deck Eng', "Agriculture.");
insert into cartablanca values(86, 'default', 'Default Deck Eng', "Judge Judy.");
insert into cartablanca values(87, 'default', 'Default Deck Eng', "Surprise sex!");
insert into cartablanca values(88, 'default', 'Default Deck Eng', "The homosexual agenda.");
insert into cartablanca values(89, 'default', 'Default Deck Eng', "Robert Dow Jr.");
insert into cartablanca values(90, 'default', 'Default Deck Eng', "The Trail of Tears.");
insert into cartablanca values(91, 'default', 'Default Deck Eng', "An M. Night Shyamalan plot twist.");
insert into cartablanca values(92, 'default', 'Default Deck Eng', "Funky fresh rhymes.");
insert into cartablanca values(93, 'default', 'Default Deck Eng', "The light of a billion sun");
insert into cartablanca values(94, 'default', 'Default Deck Eng', "Amputees.");
insert into cartablanca values(95, 'default', 'Default Deck Eng', "Throwing a virgin into a volcano.");
insert into cartablanca values(96, 'default', 'Default Deck Eng', "Italians.");
insert into cartablanca values(97, 'default', 'Default Deck Eng', "Explosions.");
insert into cartablanca values(98, 'default', 'Default Deck Eng', "A good sniff.");
insert into cartablanca values(99, 'default', 'Default Deck Eng', "Destroying the evidence.");
insert into cartablanca values(100, 'default', 'Default Deck Eng', "Children on leashes.");
insert into cartablanca values(101, 'default', 'Default Deck Eng', "Catapults.");
insert into cartablanca values(102, 'default', 'Default Deck Eng', "One trillion dollars.");
insert into cartablanca values(103, 'default', 'Default Deck Eng', "Friends with benefits.");
insert into cartablanca values(104, 'default', 'Default Deck Eng', "Dying.");
insert into cartablanca values(105, 'default', 'Default Deck Eng', "Silence.");
insert into cartablanca values(106, 'default', 'Default Deck Eng', "Growing a pair.");
insert into cartablanca values(107, 'default', 'Default Deck Eng', "YOU MUST CONSTRUCT ADDITIONAL PYLONS.");
insert into cartablanca values(108, 'default', 'Default Deck Eng', "Justin Bieber.");
insert into cartablanca values(109, 'default', 'Default Deck Eng', "The Holy Bible.");
insert into cartablanca values(110, 'default', 'Default Deck Eng', "Balls.");
insert into cartablanca values(111, 'default', 'Default Deck Eng', "Praying the gay away.");
insert into cartablanca values(112, 'default', 'Default Deck Eng', "Teenage pregnancy.");
insert into cartablanca values(113, 'default', 'Default Deck Eng', "German dungeon porn.");
insert into cartablanca values(114, 'default', 'Default Deck Eng', "The invisible hand.");
insert into cartablanca values(115, 'default', 'Default Deck Eng', "My inner demons.");
insert into cartablanca values(116, 'default', 'Default Deck Eng', "Powerful thighs.");
insert into cartablanca values(117, 'default', 'Default Deck Eng', "Getting naked and watching Nickelodeon.");
insert into cartablanca values(118, 'default', 'Default Deck Eng', "Crippling debt.");
insert into cartablanca values(119, 'default', 'Default Deck Eng', "Kamikaze pilots.");
insert into cartablanca values(120, 'default', 'Default Deck Eng', "Teaching a robot to love.");
insert into cartablanca values(121, 'default', 'Default Deck Eng', "Police brutality.");
insert into cartablanca values(122, 'default', 'Default Deck Eng', "Horse meat.");
insert into cartablanca values(123, 'default', 'Default Deck Eng', "All-you-can-eat shrimp for $4.99");
insert into cartablanca values(124, 'default', 'Default Deck Eng', "Heteronormativity.");
insert into cartablanca values(125, 'default', 'Default Deck Eng', "Michael Jackson.");
insert into cartablanca values(126, 'default', 'Default Deck Eng', "A really cool hat.");
insert into cartablanca values(127, 'default', 'Default Deck Eng', "Copping a feel.");
insert into cartablanca values(128, 'default', 'Default Deck Eng', "Crystal meth.");
insert into cartablanca values(129, 'default', 'Default Deck Eng', "Shapeshifters.");
insert into cartablanca values(130, 'default', 'Default Deck Eng', "Fingering.");
insert into cartablanca values(131, 'default', 'Default Deck Eng', "A disappointing birthday party.");
insert into cartablanca values(132, 'default', 'Default Deck Eng', "The Patriarchy.");
insert into cartablanca values(133, 'default', 'Default Deck Eng', "A bag full of Babies. ");
insert into cartablanca values(134, 'default', 'Default Deck Eng', "A sausage festival.");
insert into cartablanca values(135, 'default', 'Default Deck Eng', "The chronic.");
insert into cartablanca values(136, 'default', 'Default Deck Eng', "Eugenics.");
insert into cartablanca values(137, 'default', 'Default Deck Eng', "Synergistic management solutions.");
insert into cartablanca values(138, 'default', 'Default Deck Eng', "RoboCop.");
insert into cartablanca values(139, 'default', 'Default Deck Eng', "Serfdom.");
insert into cartablanca values(140, 'default', 'Default Deck Eng', "Stephen Hawking talking dirty.");
insert into cartablanca values(141, 'default', 'Default Deck Eng', "A man on the brink of orgasm.");
insert into cartablanca values(142, 'default', 'Default Deck Eng', "Fiery poops.");
insert into cartablanca values(143, 'default', 'Default Deck Eng', "Public ridicule");
insert into cartablanca values(144, 'default', 'Default Deck Eng', "White-man scalps.");
insert into cartablanca values(145, 'default', 'Default Deck Eng', "The morbidly obese.");
insert into cartablanca values(146, 'default', 'Default Deck Eng', "Object permanence.");
insert into cartablanca values(147, 'default', 'Default Deck Eng', "Google");
insert into cartablanca values(148, 'default', 'Default Deck Eng', "Lockjaw.");
insert into cartablanca values(149, 'default', 'Default Deck Eng', "Joe Biden.");
insert into cartablanca values(150, 'default', 'Default Deck Eng', "Bio-engineered assault turtles with acid breath.");
insert into cartablanca values(151, 'default', 'Default Deck Eng', "Wet dreams.");
insert into cartablanca values(152, 'default', 'Default Deck Eng', "Hip hop jewels.");
insert into cartablanca values(153, 'default', 'Default Deck Eng', "Firing a rifle into the air while balls deep in a squealing hog.");
insert into cartablanca values(154, 'default', 'Default Deck Eng', "Panda sex.");
insert into cartablanca values(155, 'default', 'Default Deck Eng', "Necrophilia.");
insert into cartablanca values(156, 'default', 'Default Deck Eng', "Grave robbing.");
insert into cartablanca values(157, 'default', 'Default Deck Eng', "A bleached asshole.");
insert into cartablanca values(158, 'default', 'Default Deck Eng', "Muhammad(Praise Be Unto Him).");
insert into cartablanca values(159, 'default', 'Default Deck Eng', "Multiple stab wounds.");
insert into cartablanca values(160, 'default', 'Default Deck Eng', "Daniel Radcliffe's delicious asshole.");
insert into cartablanca values(161, 'default', 'Default Deck Eng', "A monkey smoking a cigar.");
insert into cartablanca values(162, 'default', 'Default Deck Eng', "Smegma.");
insert into cartablanca values(163, 'default', 'Default Deck Eng', "A live studio audience.");
insert into cartablanca values(164, 'default', 'Default Deck Eng', "Making a pouty face.");
insert into cartablanca values(165, 'default', 'Default Deck Eng', "The violation of our most basic human rights.");
insert into cartablanca values(166, 'default', 'Default Deck Eng', "Unfathomable stupidity.");
insert into cartablanca values(167, 'default', 'Default Deck Eng', "Sunshine and rainbows.");
insert into cartablanca values(168, 'default', 'Default Deck Eng', "Whipping it out.");
insert into cartablanca values(169, 'default', 'Default Deck Eng', "The token minority.");
insert into cartablanca values(170, 'default', 'Default Deck Eng', "The terrorists.");
insert into cartablanca values(171, 'default', 'Default Deck Eng', "The Three-Fifths compromise.");
insert into cartablanca values(172, 'default', 'Default Deck Eng', "A snapping turtle biting the tip of your penis.");
insert into cartablanca values(173, 'default', 'Default Deck Eng', "Vehicular manslaughter.");
insert into cartablanca values(174, 'default', 'Default Deck Eng', "The Great Depression.");
insert into cartablanca values(175, 'default', 'Default Deck Eng', "Emotions.");
insert into cartablanca values(176, 'default', 'Default Deck Eng', "Getting so angry that you pop a boner.");
insert into cartablanca values(177, 'default', 'Default Deck Eng', "Same-sex ice dancing.");
insert into cartablanca values(178, 'default', 'Default Deck Eng', "An M16 assault rifle.");
insert into cartablanca values(179, 'default', 'Default Deck Eng', "Man meat.");
insert into cartablanca values(180, 'default', 'Default Deck Eng', "Incest.");
insert into cartablanca values(181, 'default', 'Default Deck Eng', "A foul mouth.");
insert into cartablanca values(182, 'default', 'Default Deck Eng', "Flightless birds.");
insert into cartablanca values(183, 'default', 'Default Deck Eng', "Doing the right thing.");
insert into cartablanca values(184, 'default', 'Default Deck Eng', "When you fart and a little bit comes out.");
insert into cartablanca values(185, 'default', 'Default Deck Eng', "Frolicking.");
insert into cartablanca values(186, 'default', 'Default Deck Eng', "Being a dick to children.");
insert into cartablanca values(187, 'default', 'Default Deck Eng', "Poopy diapers.");
insert into cartablanca values(188, 'default', 'Default Deck Eng', "Seeing grandma naked.");
insert into cartablanca values(189, 'default', 'Default Deck Eng', "Raptor attacks.");
insert into cartablanca values(190, 'default', 'Default Deck Eng', "Swooping.");
insert into cartablanca values(191, 'default', 'Default Deck Eng', "Concealing a bonen.");
insert into cartablanca values(192, 'default', 'Default Deck Eng', "Full frontal nudity.");
insert into cartablanca values(193, 'default', 'Default Deck Eng', "Vigorous jazz hands.");
insert into cartablanca values(194, 'default', 'Default Deck Eng', "Nipple blades.");
insert into cartablanca values(195, 'default', 'Default Deck Eng', "A bitch slap.");
insert into cartablanca values(196, 'default', 'Default Deck Eng', "Michelle Obama's arms.");
insert into cartablanca values(197, 'default', 'Default Deck Eng', "Mouth herpes.");
insert into cartablanca values(198, 'default', 'Default Deck Eng', "A robust mongoloid.");
insert into cartablanca values(199, 'default', 'Default Deck Eng', "Mutually-assu destruction.");
insert into cartablanca values(200, 'default', 'Default Deck Eng', "The Rapture.");
insert into cartablanca values(201, 'default', 'Default Deck Eng', "Road head.");
insert into cartablanca values(202, 'default', 'Default Deck Eng', "Stalin.");
insert into cartablanca values(203, 'default', 'Default Deck Eng', "Lactation.");
insert into cartablanca values(204, 'default', 'Default Deck Eng', "Hurricane Katrina.");
insert into cartablanca values(205, 'default', 'Default Deck Eng', "The true meaning of Christmas.");
insert into cartablanca values(206, 'default', 'Default Deck Eng', "Self-loathing.");
insert into cartablanca values(207, 'default', 'Default Deck Eng', "A brain tumor.");
insert into cartablanca values(208, 'default', 'Default Deck Eng', "Dead babies.");
insert into cartablanca values(209, 'default', 'Default Deck Eng', "New Age music.");
insert into cartablanca values(210, 'default', 'Default Deck Eng', "A thermonuclear detonation.");
insert into cartablanca values(211, 'default', 'Default Deck Eng', "Geese.");
insert into cartablanca values(212, 'default', 'Default Deck Eng', "Kanye West.");
insert into cartablanca values(213, 'default', 'Default Deck Eng', "God.");
insert into cartablanca values(214, 'default', 'Default Deck Eng', "A spastic nerd.");
insert into cartablanca values(215, 'default', 'Default Deck Eng', "Harry Potter erotica.");
insert into cartablanca values(216, 'default', 'Default Deck Eng', "Kids with ass cancer.");
insert into cartablanca values(217, 'default', 'Default Deck Eng', "Lumberjack fantasies.");
insert into cartablanca values(218, 'default', 'Default Deck Eng', "The American Dream.");
insert into cartablanca values(219, 'default', 'Default Deck Eng', "Puberty.");
insert into cartablanca values(220, 'default', 'Default Deck Eng', "Sweet, sweet vengeance.");
insert into cartablanca values(221, 'default', 'Default Deck Eng', "Winking at old people.");
insert into cartablanca values(222, 'default', 'Default Deck Eng', "The wonders of the Orient.");
insert into cartablanca values(223, 'default', 'Default Deck Eng', "Oompa-Loompas.");
insert into cartablanca values(224, 'default', 'Default Deck Eng', "Authentic Mexican cuisine.");
insert into cartablanca values(225, 'default', 'Default Deck Eng', "Preteens.");
insert into cartablanca values(226, 'default', 'Default Deck Eng', "The Little Engine That Could.");
insert into cartablanca values(227, 'default', 'Default Deck Eng', "A Fleshlight.");
insert into cartablanca values(228, 'default', 'Default Deck Eng', "Erectile dysfunction.");
insert into cartablanca values(229, 'default', 'Default Deck Eng', "Having anuses for eyes.");
insert into cartablanca values(230, 'default', 'Default Deck Eng', "Rush Limbaugh's soft, shitty body.");
insert into cartablanca values(231, 'default', 'Default Deck Eng', "Saxophone solos.");
insert into cartablanca values(232, 'default', 'Default Deck Eng', "Land mines.");
insert into cartablanca values(233, 'default', 'Default Deck Eng', "Running out of semen.");
insert into cartablanca values(234, 'default', 'Default Deck Eng', "Me time.");
insert into cartablanca values(235, 'default', 'Default Deck Eng', "Nickelback.");
insert into cartablanca values(236, 'default', 'Default Deck Eng', "Vigilante justice.");
insert into cartablanca values(237, 'default', 'Default Deck Eng', "The South.");
insert into cartablanca values(238, 'default', 'Default Deck Eng', "Opposable thumbs.");
insert into cartablanca values(239, 'default', 'Default Deck Eng', "Ghosts.");
insert into cartablanca values(240, 'default', 'Default Deck Eng', "Alcoholism.");
insert into cartablanca values(241, 'default', 'Default Deck Eng', "Poorly-timed Holocaust jokes.");
insert into cartablanca values(242, 'default', 'Default Deck Eng', "Inappropriate yodeling.");
insert into cartablanca values(243, 'default', 'Default Deck Eng', "Battlefield amputations.");
insert into cartablanca values(244, 'default', 'Default Deck Eng', "Exactly what you'd expect.");
insert into cartablanca values(245, 'default', 'Default Deck Eng', "A time travel paradox.");
insert into cartablanca values(246, 'default', 'Default Deck Eng', "AXE Body Spray.");
insert into cartablanca values(247, 'default', 'Default Deck Eng', "The pirate's life.");
insert into cartablanca values(248, 'default', 'Default Deck Eng', "Saying I love you.");
insert into cartablanca values(249, 'default', 'Default Deck Eng', "A sassy black woman.");
insert into cartablanca values(250, 'default', 'Default Deck Eng', "Being a motherfucking sorcerer.");
insert into cartablanca values(251, 'default', 'Default Deck Eng', "A mopey zoo lion.");
insert into cartablanca values(252, 'default', 'Default Deck Eng', "A murder most foul.");
insert into cartablanca values(253, 'default', 'Default Deck Eng', "A falcon with a cap on its head.");
insert into cartablanca values(254, 'default', 'Default Deck Eng', "Farting and walking away.");
insert into cartablanca values(255, 'default', 'Default Deck Eng', "A mating display.");
insert into cartablanca values(256, 'default', 'Default Deck Eng', "The Chinese gymnastics team.");
insert into cartablanca values(257, 'default', 'Default Deck Eng', "Friction.");
insert into cartablanca values(258, 'default', 'Default Deck Eng', "Asians who aren't good at math.");
insert into cartablanca values(259, 'default', 'Default Deck Eng', "Fear itself.");
insert into cartablanca values(260, 'default', 'Default Deck Eng', "A can of whoop-ass.");
insert into cartablanca values(261, 'default', 'Default Deck Eng', "Yeast.");
insert into cartablanca values(262, 'default', 'Default Deck Eng', "Lunchables.");
insert into cartablanca values(263, 'default', 'Default Deck Eng', "Licking things to claim them as your own.");
insert into cartablanca values(264, 'default', 'Default Deck Eng', "Vikings.");
insert into cartablanca values(265, 'default', 'Default Deck Eng', "The Kool-Aid Man.");
insert into cartablanca values(266, 'default', 'Default Deck Eng', "Hot cheese.");
insert into cartablanca values(267, 'default', 'Default Deck Eng', "Nicolas Cage.");
insert into cartablanca values(268, 'default', 'Default Deck Eng', "A defective condom.");
insert into cartablanca values(269, 'default', 'Default Deck Eng', "The inevitable heat death of the universe.");
insert into cartablanca values(270, 'default', 'Default Deck Eng', "Republicans.");
insert into cartablanca values(271, 'default', 'Default Deck Eng', "William Shatner.");
insert into cartablanca values(272, 'default', 'Default Deck Eng', "Tentacle porn.");
insert into cartablanca values(273, 'default', 'Default Deck Eng', "Sperm whales.");
insert into cartablanca values(274, 'default', 'Default Deck Eng', "Lady Gaga.");
insert into cartablanca values(275, 'default', 'Default Deck Eng', "The wrath of Vladimir Putin.");
insert into cartablanca values(276, 'default', 'Default Deck Eng', "Gloryholes.");
insert into cartablanca values(277, 'default', 'Default Deck Eng', "Daddy issues.");
insert into cartablanca values(278, 'default', 'Default Deck Eng', "A mime having a stroke.");
insert into cartablanca values(279, 'default', 'Default Deck Eng', "White people.");
insert into cartablanca values(280, 'default', 'Default Deck Eng', "A lifetime of sadness.");
insert into cartablanca values(281, 'default', 'Default Deck Eng', "Tasteful sideboob.");
insert into cartablanca values(282, 'default', 'Default Deck Eng', "A sea of troubles.");
insert into cartablanca values(283, 'default', 'Default Deck Eng', "Nazis.");
insert into cartablanca values(284, 'default', 'Default Deck Eng', "A cooler full of organs.");
insert into cartablanca values(285, 'default', 'Default Deck Eng', "Giving 110%.");
insert into cartablanca values(286, 'default', 'Default Deck Eng', "Doing it in the butt.");
insert into cartablanca values(287, 'default', 'Default Deck Eng', "John Wilkes Booth.");
insert into cartablanca values(288, 'default', 'Default Deck Eng', "Holding down a child and farting all over him.");
insert into cartablanca values(289, 'default', 'Default Deck Eng', "A homoerotic volleyball montage.");
insert into cartablanca values(290, 'default', 'Default Deck Eng', "Puppies!");
insert into cartablanca values(291, 'default', 'Default Deck Eng', "Natural male enhancement.");
insert into cartablanca values(292, 'default', 'Default Deck Eng', "Brown people.");
insert into cartablanca values(293, 'default', 'Default Deck Eng', "Dropping a chandelier on your enemies and riding the rope up");
insert into cartablanca values(294, 'default', 'Default Deck Eng', "Soup that is too hot.");
insert into cartablanca values(295, 'default', 'Default Deck Eng', "Sex with Patrick Stewart.");
insert into cartablanca values(296, 'default', 'Default Deck Eng', "Hormone injections.");
insert into cartablanca values(297, 'default', 'Default Deck Eng', "Pulling out.");
insert into cartablanca values(298, 'default', 'Default Deck Eng', "The Big Bang.");
insert into cartablanca values(299, 'default', 'Default Deck Eng', "Switching to Geico.");
insert into cartablanca values(300, 'default', 'Default Deck Eng', "Giving birth to the Antichrist.");
insert into cartablanca values(301, 'default', 'Default Deck Eng', "Dark and mysterious forces beyond our control.");
insert into cartablanca values(302, 'default', 'Default Deck Eng', "Christopher Walken.");
insert into cartablanca values(303, 'default', 'Default Deck Eng', "Count Chocula.");
insert into cartablanca values(304, 'default', 'Default Deck Eng', "The Hamburglar.");
insert into cartablanca values(305, 'default', 'Default Deck Eng', "Not reciprocating oral sex.");
insert into cartablanca values(306, 'default', 'Default Deck Eng', "Aaron Burr.");
insert into cartablanca values(307, 'default', 'Default Deck Eng', "Hot people.");
insert into cartablanca values(308, 'default', 'Default Deck Eng', "Foreskin.");
insert into cartablanca values(309, 'default', 'Default Deck Eng', "Assless chaps.");
insert into cartablanca values(310, 'default', 'Default Deck Eng', "The miracle of childbirth.");
insert into cartablanca values(311, 'default', 'Default Deck Eng', "Waiting 'til marriage.");
insert into cartablanca values(312, 'default', 'Default Deck Eng', "Two midgets shitting into a bucket");
insert into cartablanca values(313, 'default', 'Default Deck Eng', "Adderall.");
insert into cartablanca values(314, 'default', 'Default Deck Eng', "A sad handjob.");
insert into cartablanca values(315, 'default', 'Default Deck Eng', "Cheating in the Special Olympics.");
insert into cartablanca values(316, 'default', 'Default Deck Eng', "The glass ceiling.");
insert into cartablanca values(317, 'default', 'Default Deck Eng', "The Hustle.");
insert into cartablanca values(318, 'default', 'Default Deck Eng', "Miley Cyrus at 55.");
insert into cartablanca values(319, 'default', 'Default Deck Eng', "Our first chimpanzee president.");
insert into cartablanca values(320, 'default', 'Default Deck Eng', "Breaking out into song and dance.");
insert into cartablanca values(321, 'default', 'Default Deck Eng', "A Super Soaker full of cat pee.");
insert into cartablanca values(322, 'default', 'Default Deck Eng', "The Underground Railroad.");
insert into cartablanca values(323, 'default', 'Default Deck Eng', "Home video of Oprah sobbing into a Lean Cuisine.");
insert into cartablanca values(324, 'default', 'Default Deck Eng', "The Rev. Dr.Martin Luther King, Jr.");
insert into cartablanca values(325, 'default', 'Default Deck Eng', "Extremely tight pants.");
insert into cartablanca values(326, 'default', 'Default Deck Eng', "Third base.");
insert into cartablanca values(327, 'default', 'Default Deck Eng', "Waking up half-naked in a Denny's parking lot.");
insert into cartablanca values(328, 'default', 'Default Deck Eng', "The cool, refreshing taste of Pepsi.");
insert into cartablanca values(329, 'default', 'Default Deck Eng', "White privilege.");
insert into cartablanca values(330, 'default', 'Default Deck Eng', "Hope.");
insert into cartablanca values(331, 'default', 'Default Deck Eng', "Taking off your shirt.");
insert into cartablanca values(332, 'default', 'Default Deck Eng', "Smallpox blankets.");
insert into cartablanca values(333, 'default', 'Default Deck Eng', "Ethnic cleansing.");
insert into cartablanca values(334, 'default', 'Default Deck Eng', "Queefing.");
insert into cartablanca values(335, 'default', 'Default Deck Eng', "Helplessly giggling at the mention of Hutus and Tutsis.");
insert into cartablanca values(336, 'default', 'Default Deck Eng', "Getting really high.");
insert into cartablanca values(337, 'default', 'Default Deck Eng', "Natural selection.");
insert into cartablanca values(338, 'default', 'Default Deck Eng', "A gassy antelope.");
insert into cartablanca values(339, 'default', 'Default Deck Eng', "My sex life.");
insert into cartablanca values(340, 'default', 'Default Deck Eng', "Arnold Schwarzenegger.");
insert into cartablanca values(341, 'default', 'Default Deck Eng', "Pretending to care.");
insert into cartablanca values(342, 'default', 'Default Deck Eng', "Ronald Reagan.");
insert into cartablanca values(343, 'default', 'Default Deck Eng', "Toni Morrison's vagina.");
insert into cartablanca values(344, 'default', 'Default Deck Eng', "An ugly face.");
insert into cartablanca values(345, 'default', 'Default Deck Eng', "My black ass.");
insert into cartablanca values(346, 'default', 'Default Deck Eng', "BATMAN");
insert into cartablanca values(347, 'default', 'Default Deck Eng', "Homeless people.");
insert into cartablanca values(348, 'default', 'Default Deck Eng', "Racially-biased SAT questions.");
insert into cartablanca values(349, 'default', 'Default Deck Eng', "Centaurs.");
insert into cartablanca values(350, 'default', 'Default Deck Eng', "A salty surprise.");
insert into cartablanca values(351, 'default', 'Default Deck Eng', "72 virgins.");
insert into cartablanca values(352, 'default', 'Default Deck Eng', "Embryonic stem cells.");
insert into cartablanca values(353, 'default', 'Default Deck Eng', "Pixelated bukkake.");
insert into cartablanca values(354, 'default', 'Default Deck Eng', "Seppuku.");
insert into cartablanca values(355, 'default', 'Default Deck Eng', "An icepick lobotomy.");
insert into cartablanca values(356, 'default', 'Default Deck Eng', "Genuine human connection.");
insert into cartablanca values(357, 'default', 'Default Deck Eng', "Menstrual rage.");
insert into cartablanca values(358, 'default', 'Default Deck Eng', "Sexual peeing.");
insert into cartablanca values(359, 'default', 'Default Deck Eng', "An endless stream of diarrhea.");
insert into cartablanca values(360, 'default', 'Default Deck Eng', "Shaquille O'Neal's acting career.");
insert into cartablanca values(361, 'default', 'Default Deck Eng', "Horrifying laser hair removal accidents.");
insert into cartablanca values(362, 'default', 'Default Deck Eng', "Autocannibalism.");
insert into cartablanca values(363, 'default', 'Default Deck Eng', "A fetus.");
insert into cartablanca values(364, 'default', 'Default Deck Eng', "Riding off into the sunset.");
insert into cartablanca values(365, 'default', 'Default Deck Eng', "Goblins.");
insert into cartablanca values(366, 'default', 'Default Deck Eng', "Eating the last known bison.");
insert into cartablanca values(367, 'default', 'Default Deck Eng', "Shiny objects.");
insert into cartablanca values(368, 'default', 'Default Deck Eng', "Being rich.");
insert into cartablanca values(369, 'default', 'Default Deck Eng', "A Bop lt.");
insert into cartablanca values(370, 'default', 'Default Deck Eng', "Leprosy.");
insert into cartablanca values(371, 'default', 'Default Deck Eng', "World peace.");
insert into cartablanca values(372, 'default', 'Default Deck Eng', "Dick fingers.");
insert into cartablanca values(373, 'default', 'Default Deck Eng', "Chainsaws for hands.");
insert into cartablanca values(374, 'default', 'Default Deck Eng', "The Make-A-Wish Foundation.");
insert into cartablanca values(375, 'default', 'Default Deck Eng', "Penis breath.");
insert into cartablanca values(376, 'default', 'Default Deck Eng', "Laying an egg.");
insert into cartablanca values(377, 'default', 'Default Deck Eng', "The folly of man.");
insert into cartablanca values(378, 'default', 'Default Deck Eng', "My genitals.");
insert into cartablanca values(379, 'default', 'Default Deck Eng', "Grandma.");
insert into cartablanca values(380, 'default', 'Default Deck Eng', "Flesh-eating bacteria.");
insert into cartablanca values(381, 'default', 'Default Deck Eng', "Poor people.");
insert into cartablanca values(382, 'default', 'Default Deck Eng', "50,000 volts straight to the nipples.");
insert into cartablanca values(383, 'default', 'Default Deck Eng', "Active listening.");
insert into cartablanca values(384, 'default', 'Default Deck Eng', "The Ubermensch.");
insert into cartablanca values(385, 'default', 'Default Deck Eng', "Poor life choices.");
insert into cartablanca values(386, 'default', 'Default Deck Eng', "Altar boys.");
insert into cartablanca values(387, 'default', 'Default Deck Eng', "My vagina.");
insert into cartablanca values(388, 'default', 'Default Deck Eng', "Pac-Man uncontrollably guzzling cum.");
insert into cartablanca values(389, 'default', 'Default Deck Eng', "Sniffing glue.");
insert into cartablanca values(390, 'default', 'Default Deck Eng', "The placenta.");
insert into cartablanca values(391, 'default', 'Default Deck Eng', "The profoundly handicapped.");
insert into cartablanca values(392, 'default', 'Default Deck Eng', "Spontaneous human combustion.");
insert into cartablanca values(393, 'default', 'Default Deck Eng', "The KKK.");
insert into cartablanca values(394, 'default', 'Default Deck Eng', "The clitoris.");
insert into cartablanca values(395, 'default', 'Default Deck Eng', "Not wearing pants.");
insert into cartablanca values(396, 'default', 'Default Deck Eng', "Consensual sex.");
insert into cartablanca values(397, 'default', 'Default Deck Eng', "Black people.");
insert into cartablanca values(398, 'default', 'Default Deck Eng', "A bucket of fish heads.");
insert into cartablanca values(399, 'default', 'Default Deck Eng', "Hospice care.");
insert into cartablanca values(400, 'default', 'Default Deck Eng', "Passive-aggressive Post-it notes.");
insert into cartablanca values(401, 'default', 'Default Deck Eng', "Fancy Feast.");
insert into cartablanca values(402, 'default', 'Default Deck Eng', "The heart of a child.");
insert into cartablanca values(403, 'default', 'Default Deck Eng', "Crumbs all over the god damn carpet.");
insert into cartablanca values(404, 'default', 'Default Deck Eng', "Your weird brother.");
insert into cartablanca values(405, 'default', 'Default Deck Eng', "Being fat and stupid.");
insert into cartablanca values(406, 'default', 'Default Deck Eng', "Getting married,having a few kids,buying some stuff retiring to Florida and dying.");
insert into cartablanca values(407, 'default', 'Default Deck Eng', "Sean Penn.");
insert into cartablanca values(408, 'default', 'Default Deck Eng', "Sean Connery.");
insert into cartablanca values(409, 'default', 'Default Deck Eng', "Expecting a burp and vomiting on the floor.");
insert into cartablanca values(410, 'default', 'Default Deck Eng', "Wifely duties.");
insert into cartablanca values(411, 'default', 'Default Deck Eng', "A pyramid of severed heads.");
insert into cartablanca values(412, 'default', 'Default Deck Eng', "Genghis Khan.");
insert into cartablanca values(413, 'default', 'Default Deck Eng', "Historically black colleges.");
insert into cartablanca values(414, 'default', 'Default Deck Eng', "Crucifixion.");
insert into cartablanca values(415, 'default', 'Default Deck Eng', "A subscription to Men's Fitness.");
insert into cartablanca values(416, 'default', 'Default Deck Eng', "The milk man.");
insert into cartablanca values(417, 'default', 'Default Deck Eng', "Friendly fire.");
insert into cartablanca values(418, 'default', 'Default Deck Eng', "Women's suffrage.");
insert into cartablanca values(419, 'default', 'Default Deck Eng', "AIDS.");
insert into cartablanca values(420, 'default', 'Default Deck Eng', "Former President George W. Bush.");
insert into cartablanca values(421, 'default', 'Default Deck Eng', "8 oz. of sweet Mexican black-tar heroin.");
insert into cartablanca values(422, 'default', 'Default Deck Eng', "Half-assed foreplay.");
insert into cartablanca values(423, 'default', 'Default Deck Eng', "Edible underpants.");
insert into cartablanca values(424, 'default', 'Default Deck Eng', "My collection of high-tech sex toys.");
insert into cartablanca values(425, 'default', 'Default Deck Eng', "The Force.");
insert into cartablanca values(426, 'default', 'Default Deck Eng', "Bees?");
insert into cartablanca values(427, 'default', 'Default Deck Eng', "Some god-damn peace and quiet.");
insert into cartablanca values(428, 'default', 'Default Deck Eng', "Jerking off into a pool of children's tears.");
insert into cartablanca values(429, 'default', 'Default Deck Eng', "A micropig wearing a tiny raincoat and booties.");
insert into cartablanca values(430, 'default', 'Default Deck Eng', "Three dicks at the same time");
insert into cartablanca values(431, 'default', 'Default Deck Eng', "Masturbation.");
insert into cartablanca values(432, 'default', 'Default Deck Eng', "Tom Cruise.");
insert into cartablanca values(433, 'default', 'Default Deck Eng', "A balanced breakfast.");
insert into cartablanca values(434, 'default', 'Default Deck Eng', "Anal beads.");
insert into cartablanca values(435, 'default', 'Default Deck Eng', "Drinking alone.");
insert into cartablanca values(436, 'default', 'Default Deck Eng', "Cards Against Humanity.");
insert into cartablanca values(437, 'default', 'Default Deck Eng', "Coat hanger abortions.");
insert into cartablanca values(438, 'default', 'Default Deck Eng', "Used panties.");
insert into cartablanca values(439, 'default', 'Default Deck Eng', "Cuddling.");
insert into cartablanca values(440, 'default', 'Default Deck Eng', "Wiping her butt.");
insert into cartablanca values(441, 'default', 'Default Deck Eng', "Domino's oreo Dessert Pizza.");
insert into cartablanca values(442, 'default', 'Default Deck Eng', "A zesty breakfast burrito.");
insert into cartablanca values(443, 'default', 'Default Deck Eng', "Morgan Freeman's voice.");
insert into cartablanca values(444, 'default', 'Default Deck Eng', "A middle-aged man on roller skates.");
insert into cartablanca values(445, 'default', 'Default Deck Eng', "Gandhi.");
insert into cartablanca values(446, 'default', 'Default Deck Eng', "The penny whistle solo from My Heart Will Go On.");
insert into cartablanca values(447, 'default', 'Default Deck Eng', "Spectacular abs.");
insert into cartablanca values(448, 'default', 'Default Deck Eng', "Keanu Reeves.");
insert into cartablanca values(449, 'default', 'Default Deck Eng', "Child beauty pageants.");
insert into cartablanca values(450, 'default', 'Default Deck Eng', "Child abuse.");
insert into cartablanca values(451, 'default', 'Default Deck Eng', "Bill Nye the Science Guy.");
insert into cartablanca values(452, 'default', 'Default Deck Eng', "Science.");
insert into cartablanca values(453, 'default', 'Default Deck Eng', "A tribe of warrior women.");
insert into cartablanca values(454, 'default', 'Default Deck Eng', "Viagra.");
insert into cartablanca values(455, 'default', 'Default Deck Eng', "Her Majesty, Queen Elizabeth ll.");
insert into cartablanca values(456, 'default', 'Default Deck Eng', "The entire Mormon Tabernacle Choir.");
insert into cartablanca values(457, 'default', 'Default Deck Eng', "This year's mass shooting.");
insert into cartablanca values(458, 'default', 'Default Deck Eng', "Take-backsies.");
insert into cartablanca values(459, 'default', 'Default Deck Eng', "An erection that lasts longer than four hours.");
insert into cartanegra values(0, 'default', 'Default Deck Eng', 1, "How did I lose my virginity?");
insert into cartanegra values(1, 'default', 'Default Deck Eng', 1, "Why can't I sleep at night?");
insert into cartanegra values(2, 'default', 'Default Deck Eng', 1, "What's that smell?");
insert into cartanegra values(3, 'default', 'Default Deck Eng', 1, "I got 99 problems but ___ ain't one.");
insert into cartanegra values(4, 'default', 'Default Deck Eng', 1, "Maybe she's born with it. Maybe it's ___.");
insert into cartanegra values(5, 'default', 'Default Deck Eng', 1, "What's the next Happy Meal toy?");
insert into cartanegra values(6, 'default', 'Default Deck Eng', 1, "Here is the church Here is the steeple Open the doors And there is ___ .");
insert into cartanegra values(7, 'default', 'Default Deck Eng', 1, "It's a pity that kids these days are all getting involved with ___.");
insert into cartanegra values(8, 'default', 'Default Deck Eng', 1, "Today on Maury:Help! My son is ___! ");
insert into cartanegra values(9, 'default', 'Default Deck Eng', 1, "Alternative medicine is now embracing the curative powers of ___.");
insert into cartanegra values(10, 'default', 'Default Deck Eng', 2, "And the Academy Award for ___ goes to ___.");
insert into cartanegra values(11, 'default', 'Default Deck Eng', 1, "What's that sound?");
insert into cartanegra values(12, 'default', 'Default Deck Eng', 1, "What ended my last relationship?");
insert into cartanegra values(13, 'default', 'Default Deck Eng', 1, "MTV's new reality show features eight washed'up celebrities living with ___.");
insert into cartanegra values(14, 'default', 'Default Deck Eng', 1, "I drink to forget ___.");
insert into cartanegra values(15, 'default', 'Default Deck Eng', 1, "I'm sorry, Professor, but I couldn't complete my homework because of ___.");
insert into cartanegra values(16, 'default', 'Default Deck Eng', 1, "What is Batman's guilty pleasure?");
insert into cartanegra values(17, 'default', 'Default Deck Eng', 1, "___,This is the way the world ends.");
insert into cartanegra values(18, 'default', 'Default Deck Eng', 1, "What's a girl's best friend?");
insert into cartanegra values(19, 'default', 'Default Deck Eng', 1, "TSA guidelines now prohibit ___ on airplanes.");
insert into cartanegra values(20, 'default', 'Default Deck Eng', 1, "___ That's how I want to die.");
insert into cartanegra values(21, 'default', 'Default Deck Eng', 2, "For my next trick,I will pull ___ out of ___.");
insert into cartanegra values(22, 'default', 'Default Deck Eng', 1, "In the new Disney Channel Original Movie, Hannah Montana struggles with ___ for the first time.");
insert into cartanegra values(23, 'default', 'Default Deck Eng', 2, "___ is a slippery slope that leads to ___");
insert into cartanegra values(24, 'default', 'Default Deck Eng', 1, "I get by with a little help from ___.");
insert into cartanegra values(25, 'default', 'Default Deck Eng', 1, "Dear Abby,i'm having some trouble with ___ and would like your advice.");
insert into cartanegra values(26, 'default', 'Default Deck Eng', 1, "Instead of coal,Santa now gives the bad children ___.");
insert into cartanegra values(27, 'default', 'Default Deck Eng', 1, "What's the most emo?");
insert into cartanegra values(28, 'default', 'Default Deck Eng', 1, "In 1,000 years,when paper money is a distant memory, how will we pay for goods and services?");
insert into cartanegra values(29, 'default', 'Default Deck Eng', 2, "Introducing the amazing superhero and sidekick duo! it's ___ and ___!");
insert into cartanegra values(30, 'default', 'Default Deck Eng', 2, "In M. Night Shyamalan's new movie, Bruce Willis discovers that ___ had really been ___ all along.");
insert into cartanegra values(31, 'default', 'Default Deck Eng', 1, "A romantic, candlelit dinner would be incomplete without ___.");
insert into cartanegra values(32, 'default', 'Default Deck Eng', 1, "___. Betcha can't have just one!");
insert into cartanegra values(33, 'default', 'Default Deck Eng', 1, "White people like ___.");
insert into cartanegra values(34, 'default', 'Default Deck Eng', 1, "___ High five, bro.");
insert into cartanegra values(35, 'default', 'Default Deck Eng', 1, "Next from J.K. Rowling: Harry Potter and the Chamber of ___.");
insert into cartanegra values(36, 'default', 'Default Deck Eng', 1, "Introducing Xtreme Baseball! It's like baseball,but with ___!");
insert into cartanegra values(37, 'default', 'Default Deck Eng', 2, "In a world ravaged by ___ our only solace is ___.");
insert into cartanegra values(38, 'default', 'Default Deck Eng', 1, "War! What is it good for?");
insert into cartanegra values(39, 'default', 'Default Deck Eng', 1, "During sex, I like to think about ___.");
insert into cartanegra values(40, 'default', 'Default Deck Eng', 1, "What are my parents hiding from me?");
insert into cartanegra values(41, 'default', 'Default Deck Eng', 1, "What will always get you laid?");
insert into cartanegra values(42, 'default', 'Default Deck Eng', 1, "In L.A. County Jail, word is you can trade 200 cigarettes for ___.");
insert into cartanegra values(43, 'default', 'Default Deck Eng', 1, "What did I bring back from Mexico?");
insert into cartanegra values(44, 'default', 'Default Deck Eng', 1, "What don't you want to find in your Kung Pao chicken?");
insert into cartanegra values(45, 'default', 'Default Deck Eng', 1, "What will I bring back in time to convince people that I am a powerful wizard?");
insert into cartanegra values(46, 'default', 'Default Deck Eng', 1, "How am I maintaining my relationship status?");
insert into cartanegra values(47, 'default', 'Default Deck Eng', 1, "___ It's a trap!");
insert into cartanegra values(48, 'default', 'Default Deck Eng', 1, "Coming to Broadway this season,___The Musical.");
insert into cartanegra values(49, 'default', 'Default Deck Eng', 1, "While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on ___.");
insert into cartanegra values(50, 'default', 'Default Deck Eng', 1, "After the earthquake, Sean Penn brought ___ to the people of Haiti.");
insert into cartanegra values(51, 'default', 'Default Deck Eng', 1, "Next on ESPN2, the World Series of ___.");
insert into cartanegra values(52, 'default', 'Default Deck Eng', 2, "Step 1: ___, Step 2: ___,Step 3: Profit.");
insert into cartanegra values(53, 'default', 'Default Deck Eng', 2, "They said we were crazy. They said we couldn't put ___ inside of ___. They were wrong.");
insert into cartanegra values(54, 'default', 'Default Deck Eng', 1, "But before I kill you, Mr. Bond, I must show you ___.");
insert into cartanegra values(55, 'default', 'Default Deck Eng', 1, "What gives me uncontrollable gas?");
insert into cartanegra values(56, 'default', 'Default Deck Eng', 1, "The new Chevy Tahoe. With the power and space to take ___ everywhere you go.");
insert into cartanegra values(57, 'default', 'Default Deck Eng', 1, "The class field trip was completely ruined by ___.");
insert into cartanegra values(58, 'default', 'Default Deck Eng', 1, "When Pharaoh remained unmoved, Moses called down a Plague of ___.");
insert into cartanegra values(59, 'default', 'Default Deck Eng', 1, "What's my secret power?");
insert into cartanegra values(60, 'default', 'Default Deck Eng', 1, "What's there a ton of in heaven?");
insert into cartanegra values(61, 'default', 'Default Deck Eng', 1, "What would grandma find disturbing, yet oddly charming?");
insert into cartanegra values(62, 'default', 'Default Deck Eng', 2, "I never truly understood ___ until I encountered ___.");
insert into cartanegra values(63, 'default', 'Default Deck Eng', 1, "What did the U.S. airdrop to the children of Afghanistan?");
insert into cartanegra values(64, 'default', 'Default Deck Eng', 1, "What helps Obama unwind?");
insert into cartanegra values(65, 'default', 'Default Deck Eng', 1, "What did Vin Diesel eat for dinner?");
insert into cartanegra values(66, 'default', 'Default Deck Eng', 1, "___,good to the last drop.");
insert into cartanegra values(67, 'default', 'Default Deck Eng', 1, "Why am I sticky?");
insert into cartanegra values(68, 'default', 'Default Deck Eng', 1, "What gets better with age?");
insert into cartanegra values(69, 'default', 'Default Deck Eng', 1, "___, kid'tested, mother'approved.");
insert into cartanegra values(70, 'default', 'Default Deck Eng', 1, "Daddy, why is mommy crying?");
insert into cartanegra values(71, 'default', 'Default Deck Eng', 1, "What's Teach for America using to inspire inner city students to succeed?");
insert into cartanegra values(72, 'default', 'Default Deck Eng', 1, "A recent laboratory study shows that undergraduates have 50% less sex after being exposed to ___.");
insert into cartanegra values(73, 'default', 'Default Deck Eng', 1, "Life for American Indians was forever changed when the White Man introduced them to ___.");
insert into cartanegra values(74, 'default', 'Default Deck Eng', 3, "Make a haiku.");
insert into cartanegra values(75, 'default', 'Default Deck Eng', 1, "I do not know with what weapons World War III will be fought, but World War IV will be fought with ___.");
insert into cartanegra values(76, 'default', 'Default Deck Eng', 1, "Why do I hurt all over?");
insert into cartanegra values(77, 'default', 'Default Deck Eng', 1, "What am I giving up for Lent?");
insert into cartanegra values(78, 'default', 'Default Deck Eng', 1, "What's George W. Bush thinking about right now?");
insert into cartanegra values(79, 'default', 'Default Deck Eng', 1, "The Smithsonian Museum of Natural History has just opened an interactive exhibit on ___.");
insert into cartanegra values(80, 'default', 'Default Deck Eng', 1, "When I am President of the United States, I will create the Department of ___.");
insert into cartanegra values(81, 'default', 'Default Deck Eng', 2, "Lifetime presents ___ the Story of ___.");
insert into cartanegra values(82, 'default', 'Default Deck Eng', 1, "When I am a billionaire, I shall erect a 50'foot statue to commemorate ___.");
insert into cartanegra values(83, 'default', 'Default Deck Eng', 2, "When I was tripping on acid, ___ turned into ___");
insert into cartanegra values(84, 'default', 'Default Deck Eng', 2, "That's right, I killed ___, How you ask? ___.");
insert into cartanegra values(85, 'default', 'Default Deck Eng', 3, "What's my anti'drug?");
insert into cartanegra values(86, 'default', 'Default Deck Eng', 1, "___+___=___.");
insert into cartanegra values(87, 'default', 'Default Deck Eng', 1, "What never fails to liven up the party?");
insert into cartanegra values(88, 'default', 'Default Deck Eng', 1, "What's the new fad diet?");
insert into cartanegra values(89, 'default', 'Default Deck Eng', 1, "Fun tip! When your man asks you to go down on him, try surprising him with ___ instead.");