use cardshumanity;
/*delete from cartablanca where emailUsuario = "default" and nombreBaraja = "Baraja default es";
delete from cartanegra where emailUsuario = "default" and nombreBaraja = "Baraja default es";
delete from carta where emailUsuario = "default" and nombreBaraja = "Baraja default es";
delete from baraja where emailUsuario = "default" and nombreBaraja = "Baraja default es";*/

insert into Baraja values('default', 'Baraja default es', 'es');
insert into carta values(1, 'default', 'Baraja default es', "Barack Obama");
insert into cartablanca values(1, 'default', 'Baraja default es');
insert into carta values(2, 'default', 'Baraja default es', "Un Sombrero muy guay");
insert into cartablanca values(2, 'default', 'Baraja default es');
insert into carta values(3, 'default', 'Baraja default es', "Pelotas");
insert into cartablanca values(3, 'default', 'Baraja default es');
insert into carta values(4, 'default', 'Baraja default es', "Fuego Amigo");
insert into cartablanca values(4, 'default', 'Baraja default es');
insert into carta values(5, 'default', 'Baraja default es', "Christopher Walken");
insert into cartablanca values(5, 'default', 'Baraja default es');
insert into carta values(6, 'default', 'Baraja default es', "Txeroki");
insert into cartablanca values(6, 'default', 'Baraja default es');
insert into carta values(7, 'default', 'Baraja default es', "Auschwitz");
insert into cartablanca values(7, 'default', 'Baraja default es');
insert into carta values(8, 'default', 'Baraja default es', "Rito de apareamiento");
insert into cartablanca values(8, 'default', 'Baraja default es');
insert into carta values(9, 'default', 'Baraja default es', "Frigo Pie");
insert into cartablanca values(9, 'default', 'Baraja default es');
insert into carta values(10, 'default', 'Baraja default es', "Sean Connery");
insert into cartablanca values(10, 'default', 'Baraja default es');
insert into carta values(11, 'default', 'Baraja default es', "Esperanza Aguirre");
insert into cartablanca values(11, 'default', 'Baraja default es');
insert into carta values(12, 'default', 'Baraja default es', "Tirarse un pedo e irse");
insert into cartablanca values(12, 'default', 'Baraja default es');
insert into carta values(13, 'default', 'Baraja default es', "Olor a viejos");
insert into cartablanca values(13, 'default', 'Baraja default es');
insert into carta values(14, 'default', 'Baraja default es', "Keanu Reeves");
insert into cartablanca values(14, 'default', 'Baraja default es');
insert into carta values(15, 'default', 'Baraja default es', "Sean Penn");
insert into cartablanca values(15, 'default', 'Baraja default es');
insert into carta values(16, 'default', 'Baraja default es', "Correrse en una piscina llena de lagrimas de niño");
insert into cartablanca values(16, 'default', 'Baraja default es');
insert into carta values(17, 'default', 'Baraja default es', "Un pelo púbico desviado.");
insert into cartablanca values(17, 'default', 'Baraja default es');
insert into carta values(18, 'default', 'Baraja default es', "Un terrorista gracioso");
insert into cartablanca values(18, 'default', 'Baraja default es');
insert into carta values(19, 'default', 'Baraja default es', "Carne de vaca loca");
insert into cartablanca values(19, 'default', 'Baraja default es');
insert into carta values(20, 'default', 'Baraja default es', "El huracán Katrina");
insert into cartablanca values(20, 'default', 'Baraja default es');
insert into carta values(21, 'default', 'Baraja default es', "Racismo.");
insert into cartablanca values(21, 'default', 'Baraja default es');
insert into carta values(22, 'default', 'Baraja default es', "Travestis que dan el pego.");
insert into cartablanca values(22, 'default', 'Baraja default es');
insert into carta values(23, 'default', 'Baraja default es', "Tocamientos genitales.");
insert into cartablanca values(23, 'default', 'Baraja default es');
insert into carta values(24, 'default', 'Baraja default es', "El 11-M.");
insert into cartablanca values(24, 'default', 'Baraja default es');
insert into carta values(25, 'default', 'Baraja default es', "Esperar hasta el matrimonio.");
insert into cartablanca values(25, 'default', 'Baraja default es');
insert into carta values(26, 'default', 'Baraja default es', "El clitoris.");
insert into cartablanca values(26, 'default', 'Baraja default es');
insert into carta values(27, 'default', 'Baraja default es', "Tios que no vuelven a llamar.");
insert into cartablanca values(27, 'default', 'Baraja default es');
insert into carta values(28, 'default', 'Baraja default es', "Toma dos tazas.");
insert into cartablanca values(28, 'default', 'Baraja default es');
insert into carta values(29, 'default', 'Baraja default es', "Una tortuga mordiendo la punta de tu pene.");
insert into cartablanca values(29, 'default', 'Baraja default es');
insert into carta values(30, 'default', 'Baraja default es', "Pedofilos.");
insert into cartablanca values(30, 'default', 'Baraja default es');
insert into carta values(31, 'default', 'Baraja default es', "Bono.");
insert into cartablanca values(31, 'default', 'Baraja default es');
insert into carta values(32, 'default', 'Baraja default es', "Michael Jackson");
insert into cartablanca values(32, 'default', 'Baraja default es');
insert into carta values(33, 'default', 'Baraja default es', "Skeletor.");
insert into cartablanca values(33, 'default', 'Baraja default es');
insert into carta values(34, 'default', 'Baraja default es', "La cancion del Tiburon.");
insert into cartablanca values(34, 'default', 'Baraja default es');
insert into carta values(35, 'default', 'Baraja default es', "Impotencia.");
insert into cartablanca values(35, 'default', 'Baraja default es');
insert into carta values(36, 'default', 'Baraja default es', "Natalie Portman.");
insert into cartablanca values(36, 'default', 'Baraja default es');
insert into carta values(37, 'default', 'Baraja default es', "El Big Bang.");
insert into cartablanca values(37, 'default', 'Baraja default es');
insert into carta values(38, 'default', 'Baraja default es', "Bromas sobre el Holocausto en un momento inoportuno.");
insert into cartablanca values(38, 'default', 'Baraja default es');
insert into carta values(39, 'default', 'Baraja default es', "Chupar un Pirulo.");
insert into cartablanca values(39, 'default', 'Baraja default es');
insert into carta values(40, 'default', 'Baraja default es', "Gansos.");
insert into cartablanca values(40, 'default', 'Baraja default es');
insert into carta values(41, 'default', 'Baraja default es', "Abejas?");
insert into cartablanca values(41, 'default', 'Baraja default es');
insert into carta values(42, 'default', 'Baraja default es', "Los judíos.");
insert into cartablanca values(42, 'default', 'Baraja default es');
insert into carta values(43, 'default', 'Baraja default es', "Los gays.");
insert into cartablanca values(43, 'default', 'Baraja default es');
insert into carta values(44, 'default', 'Baraja default es', "SIDA.");
insert into cartablanca values(44, 'default', 'Baraja default es');
insert into carta values(45, 'default', 'Baraja default es', "Monaguillos.");
insert into cartablanca values(45, 'default', 'Baraja default es');
insert into carta values(46, 'default', 'Baraja default es', "La tuna.");
insert into cartablanca values(46, 'default', 'Baraja default es');
insert into carta values(47, 'default', 'Baraja default es', "Sobrecompensación.");
insert into cartablanca values(47, 'default', 'Baraja default es');
insert into carta values(48, 'default', 'Baraja default es', "Esas veces en las que te entra arena en la vagina.");
insert into cartablanca values(48, 'default', 'Baraja default es');
insert into carta values(49, 'default', 'Baraja default es', "Gary Coleman.");
insert into cartablanca values(49, 'default', 'Baraja default es');
insert into carta values(50, 'default', 'Baraja default es', "Una fiesta de cumpleaños decepcionante.");
insert into cartablanca values(50, 'default', 'Baraja default es');
insert into carta values(51, 'default', 'Baraja default es', "Intercambiar saludos.");
insert into cartablanca values(51, 'default', 'Baraja default es');
insert into carta values(52, 'default', 'Baraja default es', "Su Alteza Real, la Reina Isabel II.");
insert into cartablanca values(52, 'default', 'Baraja default es');
insert into carta values(53, 'default', 'Baraja default es', "Menstruación.");
insert into cartablanca values(53, 'default', 'Baraja default es');
insert into carta values(54, 'default', 'Baraja default es', "Tener un gatillazo en los preeliminares.");
insert into cartablanca values(54, 'default', 'Baraja default es');
insert into carta values(55, 'default', 'Baraja default es', "El Teletubby gay.");
insert into cartablanca values(55, 'default', 'Baraja default es');
insert into carta values(56, 'default', 'Baraja default es', "Propaganda homosexual.");
insert into cartablanca values(56, 'default', 'Baraja default es');
insert into carta values(57, 'default', 'Baraja default es', "Practicar un aborto usando una percha.");
insert into cartablanca values(57, 'default', 'Baraja default es');
insert into carta values(58, 'default', 'Baraja default es', "La Sagrada Biblia.");
insert into cartablanca values(58, 'default', 'Baraja default es');
insert into carta values(59, 'default', 'Baraja default es', "Cienciología.");
insert into cartablanca values(59, 'default', 'Baraja default es');
insert into carta values(60, 'default', 'Baraja default es', "Tom Cruise.");
insert into cartablanca values(60, 'default', 'Baraja default es');
insert into carta values(61, 'default', 'Baraja default es', "Todas las gambas que puedas comer por 4.99€.");
insert into cartablanca values(61, 'default', 'Baraja default es');
insert into carta values(62, 'default', 'Baraja default es', "Despertarse medio desnudo en el parking del McDonalds.");
insert into cartablanca values(62, 'default', 'Baraja default es');
insert into carta values(63, 'default', 'Baraja default es', "Ana Rosa Quintana.");
insert into cartablanca values(63, 'default', 'Baraja default es');
insert into carta values(64, 'default', 'Baraja default es', "Ataques de dinosaurios.");
insert into cartablanca values(64, 'default', 'Baraja default es');
insert into carta values(65, 'default', 'Baraja default es', "Protector dental.");
insert into cartablanca values(65, 'default', 'Baraja default es');
insert into carta values(66, 'default', 'Baraja default es', "Condones de sabores.");
insert into cartablanca values(66, 'default', 'Baraja default es');
insert into carta values(67, 'default', 'Baraja default es', "Abstinencia.");
insert into cartablanca values(67, 'default', 'Baraja default es');
insert into carta values(68, 'default', 'Baraja default es', "Nazis.");
insert into cartablanca values(68, 'default', 'Baraja default es');
insert into carta values(69, 'default', 'Baraja default es', "America.");
insert into cartablanca values(69, 'default', 'Baraja default es');
insert into carta values(70, 'default', 'Baraja default es', "Calentamiento global.");
insert into cartablanca values(70, 'default', 'Baraja default es');
insert into carta values(71, 'default', 'Baraja default es', "Ciencia.");
insert into cartablanca values(71, 'default', 'Baraja default es');
insert into carta values(72, 'default', 'Baraja default es', "Chupa Chups.");
insert into cartablanca values(72, 'default', 'Baraja default es');
insert into carta values(73, 'default', 'Baraja default es', "Un aumento de pechos asimetrico.");
insert into cartablanca values(73, 'default', 'Baraja default es');
insert into carta values(74, 'default', 'Baraja default es', "Hacerlo por el culo.");
insert into cartablanca values(74, 'default', 'Baraja default es');
insert into carta values(75, 'default', 'Baraja default es', "Andar como un retrasado.");
insert into cartablanca values(75, 'default', 'Baraja default es');
insert into carta values(76, 'default', 'Baraja default es', "Pezones empitonados.");
insert into cartablanca values(76, 'default', 'Baraja default es');
insert into carta values(77, 'default', 'Baraja default es', "Desodorante Axe.");
insert into cartablanca values(77, 'default', 'Baraja default es');
insert into carta values(78, 'default', 'Baraja default es', "Paris Hilton.");
insert into cartablanca values(78, 'default', 'Baraja default es');
insert into carta values(79, 'default', 'Baraja default es', "Hara - Kiri.");
insert into cartablanca values(79, 'default', 'Baraja default es');
insert into carta values(80, 'default', 'Baraja default es', "Bond, James Bond.");
insert into cartablanca values(80, 'default', 'Baraja default es');
insert into carta values(81, 'default', 'Baraja default es', "Lamer algo y luego decir que es tuyo.");
insert into cartablanca values(81, 'default', 'Baraja default es');
insert into carta values(82, 'default', 'Baraja default es', "Comer hasta vomitar.");
insert into cartablanca values(82, 'default', 'Baraja default es');
insert into carta values(83, 'default', 'Baraja default es', "Autocanibalismo.");
insert into cartablanca values(83, 'default', 'Baraja default es');
insert into carta values(84, 'default', 'Baraja default es', "Piercings genitales.");
insert into cartablanca values(84, 'default', 'Baraja default es');
insert into carta values(85, 'default', 'Baraja default es', "Esa cosa que electrocuta tus abdominales.");
insert into cartablanca values(85, 'default', 'Baraja default es');
insert into carta values(86, 'default', 'Baraja default es', "Cagar en la sopa.");
insert into cartablanca values(86, 'default', 'Baraja default es');
insert into carta values(87, 'default', 'Baraja default es', "Comportarse como un gilipollas con los niños.");
insert into cartablanca values(87, 'default', 'Baraja default es');
insert into carta values(88, 'default', 'Baraja default es', "Pedofilia.");
insert into cartablanca values(88, 'default', 'Baraja default es');
insert into carta values(89, 'default', 'Baraja default es', "Alcoholismo.");
insert into cartablanca values(89, 'default', 'Baraja default es');
insert into carta values(90, 'default', 'Baraja default es', "Un feto.");
insert into cartablanca values(90, 'default', 'Baraja default es');
insert into carta values(91, 'default', 'Baraja default es', "Que entren a robar en tu casa y que violes a los ladrones.");
insert into cartablanca values(91, 'default', 'Baraja default es');
insert into carta values(92, 'default', 'Baraja default es', "Levadura.");
insert into cartablanca values(92, 'default', 'Baraja default es');
insert into carta values(93, 'default', 'Baraja default es', "Curar la homosexualidad con la oración.");
insert into cartablanca values(93, 'default', 'Baraja default es');
insert into carta values(94, 'default', 'Baraja default es', "Kanye West.");
insert into cartablanca values(94, 'default', 'Baraja default es');
insert into carta values(95, 'default', 'Baraja default es', "Pubertad.");
insert into cartablanca values(95, 'default', 'Baraja default es');
insert into carta values(96, 'default', 'Baraja default es', "200 gramos de heroina mexicana.");
insert into cartablanca values(96, 'default', 'Baraja default es');
insert into carta values(97, 'default', 'Baraja default es', "Agricultura.");
insert into cartablanca values(97, 'default', 'Baraja default es');
insert into carta values(98, 'default', 'Baraja default es', "Dinamicas de grupo.");
insert into cartablanca values(98, 'default', 'Baraja default es');
insert into carta values(99, 'default', 'Baraja default es', "El conejo de Nesquick.");
insert into cartablanca values(99, 'default', 'Baraja default es');
insert into carta values(100, 'default', 'Baraja default es', "Trolls.");
insert into cartablanca values(100, 'default', 'Baraja default es');
insert into carta values(101, 'default', 'Baraja default es', "Un mar de problemas.");
insert into cartablanca values(101, 'default', 'Baraja default es');
insert into carta values(102, 'default', 'Baraja default es', "Obesidad.");
insert into cartablanca values(102, 'default', 'Baraja default es');
insert into carta values(103, 'default', 'Baraja default es', "Meetic.es.");
insert into cartablanca values(103, 'default', 'Baraja default es');
insert into carta values(104, 'default', 'Baraja default es', "Caballerosidad.");
insert into cartablanca values(104, 'default', 'Baraja default es');
insert into carta values(105, 'default', 'Baraja default es', "Un halcon con una gorra en la cabeza.");
insert into cartablanca values(105, 'default', 'Baraja default es');
insert into carta values(106, 'default', 'Baraja default es', "Fabada Litoral.");
insert into cartablanca values(106, 'default', 'Baraja default es');
insert into carta values(107, 'default', 'Baraja default es', "Eduard Punset.");
insert into cartablanca values(107, 'default', 'Baraja default es');
insert into carta values(108, 'default', 'Baraja default es', "Batman.");
insert into cartablanca values(108, 'default', 'Baraja default es');
insert into carta values(109, 'default', 'Baraja default es', "El cafe mas caro del Starbucks.");
insert into cartablanca values(109, 'default', 'Baraja default es');
insert into carta values(110, 'default', 'Baraja default es', "Una ensalada de Telepizza.");
insert into cartablanca values(110, 'default', 'Baraja default es');
insert into carta values(111, 'default', 'Baraja default es', "Estar en la llama.");
insert into cartablanca values(111, 'default', 'Baraja default es');
insert into carta values(112, 'default', 'Baraja default es', "Amigos que se comen todas tus patatas fritas.");
insert into cartablanca values(112, 'default', 'Baraja default es');
insert into carta values(113, 'default', 'Baraja default es', "Gente negra.");
insert into cartablanca values(113, 'default', 'Baraja default es');
insert into carta values(114, 'default', 'Baraja default es', "Ninos que fuman hierba.");
insert into cartablanca values(114, 'default', 'Baraja default es');
insert into carta values(115, 'default', 'Baraja default es', "Frank de la Jungla.");
insert into cartablanca values(115, 'default', 'Baraja default es');
insert into carta values(116, 'default', 'Baraja default es', "El KKK.");
insert into cartablanca values(116, 'default', 'Baraja default es');
insert into carta values(117, 'default', 'Baraja default es', "Preguntas de selectividad basadas en la raza.");
insert into cartablanca values(117, 'default', 'Baraja default es');
insert into carta values(118, 'default', 'Baraja default es', "Polvorones.");
insert into cartablanca values(118, 'default', 'Baraja default es');
insert into carta values(119, 'default', 'Baraja default es', "Bukkake pixelado.");
insert into cartablanca values(119, 'default', 'Baraja default es');
insert into carta values(120, 'default', 'Baraja default es', "Lluvias doradas.");
insert into cartablanca values(120, 'default', 'Baraja default es');
insert into carta values(121, 'default', 'Baraja default es', "Comerse la Nocilla a cucharadas.");
insert into cartablanca values(121, 'default', 'Baraja default es');
insert into carta values(122, 'default', 'Baraja default es', "Tiger Woods.");
insert into cartablanca values(122, 'default', 'Baraja default es');
insert into carta values(123, 'default', 'Baraja default es', "El golpe de Estado del 23 de febrero.");
insert into cartablanca values(123, 'default', 'Baraja default es');
insert into carta values(124, 'default', 'Baraja default es', "Gandhi.");
insert into cartablanca values(124, 'default', 'Baraja default es');
insert into carta values(125, 'default', 'Baraja default es', "Un curandero.");
insert into cartablanca values(125, 'default', 'Baraja default es');
insert into carta values(126, 'default', 'Baraja default es', "Hacer pucheritos.");
insert into cartablanca values(126, 'default', 'Baraja default es');
insert into carta values(127, 'default', 'Baraja default es', "Limpieza etnica.");
insert into cartablanca values(127, 'default', 'Baraja default es');
insert into carta values(128, 'default', 'Baraja default es', "Phoskitos.");
insert into cartablanca values(128, 'default', 'Baraja default es');
insert into carta values(129, 'default', 'Baraja default es', "Mi coleccion de juguetes sexuales de alta tecnologia.");
insert into cartablanca values(129, 'default', 'Baraja default es');
insert into carta values(130, 'default', 'Baraja default es', "Huevos de pterodactilo.");
insert into cartablanca values(130, 'default', 'Baraja default es');
insert into carta values(131, 'default', 'Baraja default es', "Ronald Reagan.");
insert into cartablanca values(131, 'default', 'Baraja default es');
insert into carta values(132, 'default', 'Baraja default es', "Will Smith.");
insert into cartablanca values(132, 'default', 'Baraja default es');
insert into carta values(133, 'default', 'Baraja default es', "Dr. Martin Luther King, Jr.");
insert into cartablanca values(133, 'default', 'Baraja default es');
insert into carta values(134, 'default', 'Baraja default es', "Esclavitud.");
insert into cartablanca values(134, 'default', 'Baraja default es');
insert into carta values(135, 'default', 'Baraja default es', "Jagerbomb.");
insert into cartablanca values(135, 'default', 'Baraja default es');
insert into carta values(136, 'default', 'Baraja default es', "Fantasmas.");
insert into cartablanca values(136, 'default', 'Baraja default es');
insert into carta values(137, 'default', 'Baraja default es', "Seleccion natural.");
insert into cartablanca values(137, 'default', 'Baraja default es');
insert into carta values(138, 'default', 'Baraja default es', "Espinete.");
insert into cartablanca values(138, 'default', 'Baraja default es');
insert into carta values(139, 'default', 'Baraja default es', "Sufragio femenino.");
insert into cartablanca values(139, 'default', 'Baraja default es');
insert into carta values(140, 'default', 'Baraja default es', "Diseño inteligente.");
insert into cartablanca values(140, 'default', 'Baraja default es');
insert into carta values(141, 'default', 'Baraja default es', "Levantar el cuello de la camisa.");
insert into cartablanca values(141, 'default', 'Baraja default es');
insert into carta values(142, 'default', 'Baraja default es', "Las vias del metro.");
insert into cartablanca values(142, 'default', 'Baraja default es');
insert into carta values(143, 'default', 'Baraja default es', "Necrofilia.");
insert into cartablanca values(143, 'default', 'Baraja default es');
insert into carta values(144, 'default', 'Baraja default es', "Torsion testicular.");
insert into cartablanca values(144, 'default', 'Baraja default es');
insert into carta values(145, 'default', 'Baraja default es', "Lactancia.");
insert into cartablanca values(145, 'default', 'Baraja default es');
insert into carta values(146, 'default', 'Baraja default es', "Dulce, dulce venganza.");
insert into cartablanca values(146, 'default', 'Baraja default es');
insert into carta values(147, 'default', 'Baraja default es', "Minas terrestres.");
insert into cartablanca values(147, 'default', 'Baraja default es');
insert into carta values(148, 'default', 'Baraja default es', "Cabras comiendo latas.");
insert into cartablanca values(148, 'default', 'Baraja default es');
insert into carta values(149, 'default', 'Baraja default es', "Los discapacitados profundos.");
insert into cartablanca values(149, 'default', 'Baraja default es');
insert into carta values(150, 'default', 'Baraja default es', "Profesores sustitutos.");
insert into cartablanca values(150, 'default', 'Baraja default es');
insert into carta values(151, 'default', 'Baraja default es', "Los gitanos.");
insert into cartablanca values(151, 'default', 'Baraja default es');
insert into carta values(152, 'default', 'Baraja default es', "Elmo cosquillas.");
insert into cartablanca values(152, 'default', 'Baraja default es');
insert into carta values(153, 'default', 'Baraja default es', "Esta respuesta es post-moderna.");
insert into cartablanca values(153, 'default', 'Baraja default es');
insert into carta values(154, 'default', 'Baraja default es', "Dos enanos cagando en un cubo.");
insert into cartablanca values(154, 'default', 'Baraja default es');
insert into carta values(155, 'default', 'Baraja default es', "Mi alma.");
insert into cartablanca values(155, 'default', 'Baraja default es');
insert into carta values(156, 'default', 'Baraja default es', "Mis genitales.");
insert into cartablanca values(156, 'default', 'Baraja default es');
insert into carta values(157, 'default', 'Baraja default es', "Hacerlo con otra persona delante de tu novia.");
insert into cartablanca values(157, 'default', 'Baraja default es');
insert into carta values(158, 'default', 'Baraja default es', "Pasivo-agresividad.");
insert into cartablanca values(158, 'default', 'Baraja default es');
insert into carta values(159, 'default', 'Baraja default es', "DogChow.");
insert into cartablanca values(159, 'default', 'Baraja default es');
insert into carta values(160, 'default', 'Baraja default es', "Transporte de fluidos.");
insert into cartablanca values(160, 'default', 'Baraja default es');
insert into carta values(161, 'default', 'Baraja default es', "Combustion humana espontanea.");
insert into cartablanca values(161, 'default', 'Baraja default es');
insert into carta values(162, 'default', 'Baraja default es', "La marcha atras.");
insert into cartablanca values(162, 'default', 'Baraja default es');
insert into carta values(163, 'default', 'Baraja default es', "Otra maldita pelicula de vampiros.");
insert into cartablanca values(163, 'default', 'Baraja default es');
insert into carta values(164, 'default', 'Baraja default es', "El perro de Chocapic.");
insert into cartablanca values(164, 'default', 'Baraja default es');
insert into carta values(165, 'default', 'Baraja default es', "Justin Bieber.");
insert into cartablanca values(165, 'default', 'Baraja default es');
insert into carta values(166, 'default', 'Baraja default es', "Heath Ledger.");
insert into cartablanca values(166, 'default', 'Baraja default es');
insert into carta values(167, 'default', 'Baraja default es', "Tiempo para uno mismo.");
insert into cartablanca values(167, 'default', 'Baraja default es');
insert into carta values(168, 'default', 'Baraja default es', "Incesto.");
insert into cartablanca values(168, 'default', 'Baraja default es');
insert into carta values(169, 'default', 'Baraja default es', "Tension sexual.");
insert into cartablanca values(169, 'default', 'Baraja default es');
insert into carta values(170, 'default', 'Baraja default es', "La sangre de Cristo.");
insert into cartablanca values(170, 'default', 'Baraja default es');
insert into carta values(171, 'default', 'Baraja default es', "Mahoma.");
insert into cartablanca values(171, 'default', 'Baraja default es');
insert into carta values(172, 'default', 'Baraja default es', "Emociones.");
insert into cartablanca values(172, 'default', 'Baraja default es');
insert into carta values(173, 'default', 'Baraja default es', "Viagra.");
insert into cartablanca values(173, 'default', 'Baraja default es');
insert into carta values(174, 'default', 'Baraja default es', "Ser rico.");
insert into cartablanca values(174, 'default', 'Baraja default es');
insert into carta values(175, 'default', 'Baraja default es', "Fantasias con leñadores.");
insert into cartablanca values(175, 'default', 'Baraja default es');
insert into carta values(176, 'default', 'Baraja default es', "Padres muertos.");
insert into cartablanca values(176, 'default', 'Baraja default es');
insert into carta values(177, 'default', 'Baraja default es', "Chupar algunas pollas para no ser reclutado.");
insert into cartablanca values(177, 'default', 'Baraja default es');
insert into carta values(178, 'default', 'Baraja default es', "Una pistola de agua llena de meado de gato.");
insert into cartablanca values(178, 'default', 'Baraja default es');
insert into carta values(179, 'default', 'Baraja default es', "Poluciones nocturnas.");
insert into cartablanca values(179, 'default', 'Baraja default es');
insert into carta values(180, 'default', 'Baraja default es', "Ser fabuloso.");
insert into cartablanca values(180, 'default', 'Baraja default es');
insert into carta values(181, 'default', 'Baraja default es', "Arnold Schwarzenegger.");
insert into cartablanca values(181, 'default', 'Baraja default es');
insert into carta values(182, 'default', 'Baraja default es', "Esbozar una sonrisa ante la mencion de Camboya.");
insert into cartablanca values(182, 'default', 'Baraja default es');
insert into carta values(183, 'default', 'Baraja default es', "Motosierras en vez de manos.");
insert into cartablanca values(183, 'default', 'Baraja default es');
insert into carta values(184, 'default', 'Baraja default es', "Darth Vader.");
insert into cartablanca values(184, 'default', 'Baraja default es');
insert into carta values(185, 'default', 'Baraja default es', "Bob Esponja.");
insert into cartablanca values(185, 'default', 'Baraja default es');
insert into carta values(186, 'default', 'Baraja default es', "Atun en lata con extra de delfin.");
insert into cartablanca values(186, 'default', 'Baraja default es');
insert into carta values(187, 'default', 'Baraja default es', "Vikingos.");
insert into cartablanca values(187, 'default', 'Baraja default es');
insert into carta values(188, 'default', 'Baraja default es', "El corazon de un niño.");
insert into cartablanca values(188, 'default', 'Baraja default es');
insert into carta values(189, 'default', 'Baraja default es', "Lepra.");
insert into cartablanca values(189, 'default', 'Baraja default es');
insert into carta values(190, 'default', 'Baraja default es', "Britney Spears a los 55.");
insert into cartablanca values(190, 'default', 'Baraja default es');
insert into carta values(191, 'default', 'Baraja default es', "Un buen salchichon.");
insert into cartablanca values(191, 'default', 'Baraja default es');
insert into carta values(192, 'default', 'Baraja default es', "Asiaticos que no son muy buenos en mates.");
insert into cartablanca values(192, 'default', 'Baraja default es');
insert into carta values(193, 'default', 'Baraja default es', "Una gran expectativa sobre nada.");
insert into cartablanca values(193, 'default', 'Baraja default es');
insert into carta values(194, 'default', 'Baraja default es', "Una rascada clandestina de culo.");
insert into cartablanca values(194, 'default', 'Baraja default es');
insert into carta values(195, 'default', 'Baraja default es', "Polvo de angel.");
insert into cartablanca values(195, 'default', 'Baraja default es');
insert into carta values(196, 'default', 'Baraja default es', "Decirle adios a Dios.");
insert into cartablanca values(196, 'default', 'Baraja default es');
insert into carta values(197, 'default', 'Baraja default es', "Un agujero del culo blanqueado.");
insert into cartablanca values(197, 'default', 'Baraja default es');
insert into carta values(198, 'default', 'Baraja default es', "La placenta.");
insert into cartablanca values(198, 'default', 'Baraja default es');
insert into carta values(199, 'default', 'Baraja default es', "Yo nunca.");
insert into cartablanca values(199, 'default', 'Baraja default es');
insert into carta values(200, 'default', 'Baraja default es', "Familias gitanas.");
insert into cartablanca values(200, 'default', 'Baraja default es');
insert into carta values(201, 'default', 'Baraja default es', "Cards Against Humanity.");
insert into cartablanca values(201, 'default', 'Baraja default es');
insert into carta values(202, 'default', 'Baraja default es', "Empollones.");
insert into cartablanca values(202, 'default', 'Baraja default es');
insert into carta values(203, 'default', 'Baraja default es', "Destruccion mutua asegurada.");
insert into cartablanca values(203, 'default', 'Baraja default es');
insert into carta values(204, 'default', 'Baraja default es', "Miedo a los desconocidos.");
insert into cartablanca values(204, 'default', 'Baraja default es');
insert into carta values(205, 'default', 'Baraja default es', "Un bocata de albondigas.");
insert into cartablanca values(205, 'default', 'Baraja default es');
insert into carta values(206, 'default', 'Baraja default es', "ldiotas con sus iPhones.");
insert into cartablanca values(206, 'default', 'Baraja default es');
insert into carta values(207, 'default', 'Baraja default es', "Declaracion de los Derechos Humanos.");
insert into cartablanca values(207, 'default', 'Baraja default es');
insert into carta values(208, 'default', 'Baraja default es', "Preadolescentes.");
insert into cartablanca values(208, 'default', 'Baraja default es');
insert into carta values(209, 'default', 'Baraja default es', "Existencialistas.");
insert into cartablanca values(209, 'default', 'Baraja default es');
insert into carta values(210, 'default', 'Baraja default es', "Baltasar Garzon.");
insert into cartablanca values(210, 'default', 'Baraja default es');
insert into carta values(211, 'default', 'Baraja default es', "Esmegma.");
insert into cartablanca values(211, 'default', 'Baraja default es');
insert into carta values(212, 'default', 'Baraja default es', "Morir de disenteria.");
insert into cartablanca values(212, 'default', 'Baraja default es');
insert into carta values(213, 'default', 'Baraja default es', "Los ninos de la guerra.");
insert into cartablanca values(213, 'default', 'Baraja default es');
insert into carta values(214, 'default', 'Baraja default es', "El Papa.");
insert into cartablanca values(214, 'default', 'Baraja default es');
insert into carta values(215, 'default', 'Baraja default es', "William Shatner.");
insert into cartablanca values(215, 'default', 'Baraja default es');
insert into carta values(216, 'default', 'Baraja default es', "Envidia de pene.");
insert into cartablanca values(216, 'default', 'Baraja default es');
insert into carta values(217, 'default', 'Baraja default es', "Complejo de Edipo.");
insert into cartablanca values(217, 'default', 'Baraja default es');
insert into carta values(218, 'default', 'Baraja default es', "Soy amigo de tu padre en Facebook.");
insert into cartablanca values(218, 'default', 'Baraja default es');
insert into carta values(219, 'default', 'Baraja default es', "Genghis Khan.");
insert into cartablanca values(219, 'default', 'Baraja default es');
insert into carta values(220, 'default', 'Baraja default es', "Una tortura china.");
insert into cartablanca values(220, 'default', 'Baraja default es');
insert into carta values(221, 'default', 'Baraja default es', "Mi vida sexual.");
insert into cartablanca values(221, 'default', 'Baraja default es');
insert into carta values(222, 'default', 'Baraja default es', "Oompa Loompas.");
insert into cartablanca values(222, 'default', 'Baraja default es');
insert into carta values(223, 'default', 'Baraja default es', "Un giro de guion de M. Night Shyamalan.");
insert into cartablanca values(223, 'default', 'Baraja default es');
insert into carta values(224, 'default', 'Baraja default es', "Tercera base.");
insert into cartablanca values(224, 'default', 'Baraja default es');
insert into carta values(225, 'default', 'Baraja default es', "Dejar un mensaje de voz incomodo.");
insert into cartablanca values(225, 'default', 'Baraja default es');
insert into carta values(226, 'default', 'Baraja default es', "Hacerse un dedo.");
insert into cartablanca values(226, 'default', 'Baraja default es');
insert into carta values(227, 'default', 'Baraja default es', "Jose Maria Aznar.");
insert into cartablanca values(227, 'default', 'Baraja default es');
insert into carta values(228, 'default', 'Baraja default es', "Gente que huele sus propios calcetines.");
insert into cartablanca values(228, 'default', 'Baraja default es');
insert into carta values(229, 'default', 'Baraja default es', "Catapultas.");
insert into cartablanca values(229, 'default', 'Baraja default es');
insert into carta values(230, 'default', 'Baraja default es', "Semen de ballena.");
insert into cartablanca values(230, 'default', 'Baraja default es');
insert into carta values(231, 'default', 'Baraja default es', "Baron Rojo.");
insert into cartablanca values(231, 'default', 'Baraja default es');
insert into carta values(232, 'default', 'Baraja default es', "Los Pecos.");
insert into cartablanca values(232, 'default', 'Baraja default es');
insert into carta values(233, 'default', 'Baraja default es', "Comer sandia.");
insert into cartablanca values(233, 'default', 'Baraja default es');
insert into carta values(234, 'default', 'Baraja default es', "Un hombre de mediana edad en patines.");
insert into cartablanca values(234, 'default', 'Baraja default es');
insert into carta values(235, 'default', 'Baraja default es', "Artefactos explosivos caseros.");
insert into cartablanca values(235, 'default', 'Baraja default es');
insert into carta values(236, 'default', 'Baraja default es', "Estrogeno. ");
insert into cartablanca values(236, 'default', 'Baraja default es');
insert into carta values(237, 'default', 'Baraja default es', "Una mujer negra descarada.");
insert into cartablanca values(237, 'default', 'Baraja default es');
insert into carta values(238, 'default', 'Baraja default es', "Peleas de pollos.");
insert into cartablanca values(238, 'default', 'Baraja default es');
insert into carta values(239, 'default', 'Baraja default es', "Manazas.");
insert into cartablanca values(239, 'default', 'Baraja default es');
insert into carta values(240, 'default', 'Baraja default es', "Lesbianas nazis borrachas que dan palizas.");
insert into cartablanca values(240, 'default', 'Baraja default es');
insert into carta values(241, 'default', 'Baraja default es', "Ejercicios Vaginales.");
insert into cartablanca values(241, 'default', 'Baraja default es');
insert into carta values(242, 'default', 'Baraja default es', "Porno aleman sadomasoquista.");
insert into cartablanca values(242, 'default', 'Baraja default es');
insert into carta values(243, 'default', 'Baraja default es', "Gloryholes.");
insert into cartablanca values(243, 'default', 'Baraja default es');
insert into carta values(244, 'default', 'Baraja default es', "Cachorritos!");
insert into cartablanca values(244, 'default', 'Baraja default es');
insert into carta values(245, 'default', 'Baraja default es', "Una paja triste.");
insert into cartablanca values(245, 'default', 'Baraja default es');
insert into carta values(246, 'default', 'Baraja default es', "Felacion al volante.");
insert into cartablanca values(246, 'default', 'Baraja default es');
insert into carta values(247, 'default', 'Baraja default es', "La abuelita.");
insert into cartablanca values(247, 'default', 'Baraja default es');
insert into carta values(248, 'default', 'Baraja default es', "Tener la mandibula inmobilizada.");
insert into cartablanca values(248, 'default', 'Baraja default es');
insert into carta values(249, 'default', 'Baraja default es', "Un micropene.");
insert into cartablanca values(249, 'default', 'Baraja default es');
insert into carta values(250, 'default', 'Baraja default es', "Sentir miedo de ti mismo.");
insert into cartablanca values(250, 'default', 'Baraja default es');
insert into carta values(251, 'default', 'Baraja default es', "Pajaros que no pueden volar.");
insert into cartablanca values(251, 'default', 'Baraja default es');
insert into carta values(252, 'default', 'Baraja default es', "Ropa interior comestible.");
insert into cartablanca values(252, 'default', 'Baraja default es');
insert into carta values(253, 'default', 'Baraja default es', "Un malentendido guarrete.");
insert into cartablanca values(253, 'default', 'Baraja default es');
insert into carta values(254, 'default', 'Baraja default es', "Herpes labial.");
insert into cartablanca values(254, 'default', 'Baraja default es');
insert into carta values(255, 'default', 'Baraja default es', "La trama de una pelicula de Michael Bay.");
insert into cartablanca values(255, 'default', 'Baraja default es');
insert into carta values(256, 'default', 'Baraja default es', "Abdominales espectaculares");
insert into cartablanca values(256, 'default', 'Baraja default es');
insert into carta values(257, 'default', 'Baraja default es', "Don Limpio,justo detras de ti.");
insert into cartablanca values(257, 'default', 'Baraja default es');
insert into carta values(258, 'default', 'Baraja default es', "Sexo con señoras gordas.");
insert into cartablanca values(258, 'default', 'Baraja default es');
insert into carta values(259, 'default', 'Baraja default es', "Robert Downey,Jr.");
insert into cartablanca values(259, 'default', 'Baraja default es');
insert into carta values(260, 'default', 'Baraja default es', "Ir a una orgia solo por la comida.");
insert into cartablanca values(260, 'default', 'Baraja default es');
insert into carta values(261, 'default', 'Baraja default es', "Zorritas.");
insert into cartablanca values(261, 'default', 'Baraja default es');
insert into carta values(262, 'default', 'Baraja default es', "Una explosion termonuclear.");
insert into cartablanca values(262, 'default', 'Baraja default es');
insert into carta values(263, 'default', 'Baraja default es', "Un molino lleno de cadaveres.");
insert into cartablanca values(263, 'default', 'Baraja default es');
insert into carta values(264, 'default', 'Baraja default es', "El Santiago Bernabeu.");
insert into cartablanca values(264, 'default', 'Baraja default es');
insert into carta values(265, 'default', 'Baraja default es', "Pezones que se escapan del vestido.");
insert into cartablanca values(265, 'default', 'Baraja default es');
insert into carta values(266, 'default', 'Baraja default es', "Musica New Age.");
insert into cartablanca values(266, 'default', 'Baraja default es');
insert into carta values(267, 'default', 'Baraja default es', "Solos de saxofon.");
insert into cartablanca values(267, 'default', 'Baraja default es');
insert into carta values(268, 'default', 'Baraja default es', "Masturbacion.");
insert into cartablanca values(268, 'default', 'Baraja default es');
insert into carta values(269, 'default', 'Baraja default es', "Prepucio.");
insert into cartablanca values(269, 'default', 'Baraja default es');
insert into carta values(270, 'default', 'Baraja default es', "Quitarte la camiseta.");
insert into cartablanca values(270, 'default', 'Baraja default es');
insert into carta values(271, 'default', 'Baraja default es', "Tamborileros.");
insert into cartablanca values(271, 'default', 'Baraja default es');
insert into carta values(272, 'default', 'Baraja default es', "Seduccion.");
insert into cartablanca values(272, 'default', 'Baraja default es');
insert into carta values(273, 'default', 'Baraja default es', "Gente pobre.");
insert into cartablanca values(273, 'default', 'Baraja default es');
insert into carta values(274, 'default', 'Baraja default es', "Gente sin hogar.");
insert into cartablanca values(274, 'default', 'Baraja default es');
insert into carta values(275, 'default', 'Baraja default es', "Arcoiris y rayos de sol.");
insert into cartablanca values(275, 'default', 'Baraja default es');
insert into carta values(276, 'default', 'Baraja default es', "Una LAN party.");
insert into cartablanca values(276, 'default', 'Baraja default es');
insert into carta values(277, 'default', 'Baraja default es', "Follamigos.");
insert into cartablanca values(277, 'default', 'Baraja default es');
insert into carta values(278, 'default', 'Baraja default es', "Gancho de izquierda.");
insert into cartablanca values(278, 'default', 'Baraja default es');
insert into carta values(279, 'default', 'Baraja default es', "Limpiarle el culo.");
insert into cartablanca values(279, 'default', 'Baraja default es');
insert into carta values(280, 'default', 'Baraja default es', "Focusin.");
insert into cartablanca values(280, 'default', 'Baraja default es');
insert into carta values(281, 'default', 'Baraja default es', "Muestras gratuitas.");
insert into cartablanca values(281, 'default', 'Baraja default es');
insert into carta values(282, 'default', 'Baraja default es', "Gladiadores Americanos.");
insert into cartablanca values(282, 'default', 'Baraja default es');
insert into carta values(283, 'default', 'Baraja default es', "Mear una piedra del riñon.");
insert into cartablanca values(283, 'default', 'Baraja default es');
insert into carta values(284, 'default', 'Baraja default es', "Accidentes de caza.");
insert into cartablanca values(284, 'default', 'Baraja default es');
insert into carta values(285, 'default', 'Baraja default es', "Enfermedad de las vacas locas.");
insert into cartablanca values(285, 'default', 'Baraja default es');
insert into carta values(286, 'default', 'Baraja default es', "Bolsitas de te.");
insert into cartablanca values(286, 'default', 'Baraja default es');
insert into carta values(287, 'default', 'Baraja default es', "Paisanos sin culo.");
insert into cartablanca values(287, 'default', 'Baraja default es');
insert into carta values(288, 'default', 'Baraja default es', "El sur.");
insert into cartablanca values(288, 'default', 'Baraja default es');
insert into carta values(289, 'default', 'Baraja default es', "Meterse una buena raya.");
insert into cartablanca values(289, 'default', 'Baraja default es');
insert into carta values(290, 'default', 'Baraja default es', "Echar un vistazo.");
insert into cartablanca values(290, 'default', 'Baraja default es');
insert into carta values(291, 'default', 'Baraja default es', "Piruletas enormes.");
insert into cartablanca values(291, 'default', 'Baraja default es');
insert into carta values(292, 'default', 'Baraja default es', "Heineken.");
insert into cartablanca values(292, 'default', 'Baraja default es');
insert into carta values(293, 'default', 'Baraja default es', "Federico Jimenez Losantos.");
insert into cartablanca values(293, 'default', 'Baraja default es');
insert into carta values(294, 'default', 'Baraja default es', "Un canalillo generoso.");
insert into cartablanca values(294, 'default', 'Baraja default es');
insert into carta values(295, 'default', 'Baraja default es', "Chester Cheetah.");
insert into cartablanca values(295, 'default', 'Baraja default es');
insert into carta values(296, 'default', 'Baraja default es', "Aguafiestas.");
insert into cartablanca values(296, 'default', 'Baraja default es');
insert into carta values(297, 'default', 'Baraja default es', "Musica turbo-folk de Europa del este.");
insert into cartablanca values(297, 'default', 'Baraja default es');
insert into carta values(298, 'default', 'Baraja default es', "Cagarse encima.");
insert into cartablanca values(298, 'default', 'Baraja default es');
insert into carta values(299, 'default', 'Baraja default es', "Viejos japoneses.");
insert into cartablanca values(299, 'default', 'Baraja default es');
insert into carta values(300, 'default', 'Baraja default es', "Gente blanca.");
insert into cartablanca values(300, 'default', 'Baraja default es');
insert into carta values(301, 'default', 'Baraja default es', "Una ereccion que dura mas de cuatro horas.");
insert into cartablanca values(301, 'default', 'Baraja default es');
insert into carta values(302, 'default', 'Baraja default es', "Pavonearse.");
insert into cartablanca values(302, 'default', 'Baraja default es');
insert into carta values(303, 'default', 'Baraja default es', "Porno con tentaculos.");
insert into cartablanca values(303, 'default', 'Baraja default es');
insert into carta values(304, 'default', 'Baraja default es', "El perineo.");
insert into cartablanca values(304, 'default', 'Baraja default es');
insert into carta values(305, 'default', 'Baraja default es', "El Cascanueces.");
insert into cartablanca values(305, 'default', 'Baraja default es');
insert into carta values(306, 'default', 'Baraja default es', "Barriga en forma de culo.");
insert into cartablanca values(306, 'default', 'Baraja default es');
insert into carta values(307, 'default', 'Baraja default es', "Twitteando.");
insert into cartablanca values(307, 'default', 'Baraja default es');
insert into carta values(308, 'default', 'Baraja default es', "Amputados.");
insert into cartablanca values(308, 'default', 'Baraja default es');
insert into carta values(309, 'default', 'Baraja default es', "Patinaje artistico sobre hielo con personas del mismo sexo.");
insert into cartablanca values(309, 'default', 'Baraja default es');
insert into carta values(310, 'default', 'Baraja default es', "El equipo de gimnasia chino.");
insert into cartablanca values(310, 'default', 'Baraja default es');
insert into carta values(311, 'default', 'Baraja default es', "Labios vaginales enormes.");
insert into cartablanca values(311, 'default', 'Baraja default es');
insert into carta values(312, 'default', 'Baraja default es', "Una vida de tristeza.");
insert into cartablanca values(312, 'default', 'Baraja default es');
insert into carta values(313, 'default', 'Baraja default es', "Asaltar tumbas.");
insert into cartablanca values(313, 'default', 'Baraja default es');
insert into carta values(314, 'default', 'Baraja default es', "Ponerse la ropa interior al reves para no tener que lavarla.");
insert into cartablanca values(314, 'default', 'Baraja default es');
insert into carta values(315, 'default', 'Baraja default es', "Sindrome de colon irritable.");
insert into cartablanca values(315, 'default', 'Baraja default es');
insert into carta values(316, 'default', 'Baraja default es', "La paz mundial.");
insert into cartablanca values(316, 'default', 'Baraja default es');
insert into carta values(317, 'default', 'Baraja default es', "Centauros.");
insert into cartablanca values(317, 'default', 'Baraja default es');
insert into carta values(318, 'default', 'Baraja default es', "Bajas civiles.");
insert into cartablanca values(318, 'default', 'Baraja default es');
insert into carta values(319, 'default', 'Baraja default es', "La Macarena.");
insert into cartablanca values(319, 'default', 'Baraja default es');
insert into carta values(320, 'default', 'Baraja default es', "La carrera de actor de Shaquille O'Neal");
insert into cartablanca values(320, 'default', 'Baraja default es');
insert into carta values(321, 'default', 'Baraja default es', "Judios con el pelo a lo afro.");
insert into cartablanca values(321, 'default', 'Baraja default es');
insert into carta values(322, 'default', 'Baraja default es', "Gente cachonda.");
insert into cartablanca values(322, 'default', 'Baraja default es');
insert into carta values(323, 'default', 'Baraja default es', "El testiculo perdido de Lance Armstrong.");
insert into cartablanca values(323, 'default', 'Baraja default es');
insert into carta values(324, 'default', 'Baraja default es', "Stephen Hawking diciendo guarradas.");
insert into cartablanca values(324, 'default', 'Baraja default es');
insert into carta values(325, 'default', 'Baraja default es', "Chicas que no deberian desmadrarse.");
insert into cartablanca values(325, 'default', 'Baraja default es');
insert into carta values(326, 'default', 'Baraja default es', "ltalianos.");
insert into cartablanca values(326, 'default', 'Baraja default es');
insert into carta values(327, 'default', 'Baraja default es', "Mi relacion de pareja.");
insert into cartablanca values(327, 'default', 'Baraja default es');
insert into carta values(328, 'default', 'Baraja default es', "Pilotos kamikaze.");
insert into cartablanca values(328, 'default', 'Baraja default es');
insert into carta values(329, 'default', 'Baraja default es', "Arcadas.");
insert into cartablanca values(329, 'default', 'Baraja default es');
insert into carta values(330, 'default', 'Baraja default es', "Represion.");
insert into cartablanca values(330, 'default', 'Baraja default es');
insert into carta values(331, 'default', 'Baraja default es', "Cortar cabelleras.");
insert into cartablanca values(331, 'default', 'Baraja default es');
insert into carta values(332, 'default', 'Baraja default es', "Trabajar como un chino.");
insert into cartablanca values(332, 'default', 'Baraja default es');
insert into carta values(333, 'default', 'Baraja default es', "Francisco Franco.");
insert into cartablanca values(333, 'default', 'Baraja default es');
insert into carta values(334, 'default', 'Baraja default es', "2 Girls 1 Cup.");
insert into cartablanca values(334, 'default', 'Baraja default es');
insert into carta values(335, 'default', 'Baraja default es', "Bolas chinas.");
insert into cartablanca values(335, 'default', 'Baraja default es');
insert into carta values(336, 'default', 'Baraja default es', "Concursos de belleza infantil.");
insert into cartablanca values(336, 'default', 'Baraja default es');
insert into carta values(337, 'default', 'Baraja default es', "Se ha escrito un crimen.");
insert into cartablanca values(337, 'default', 'Baraja default es');
insert into carta values(338, 'default', 'Baraja default es', "Friccion");
insert into cartablanca values(338, 'default', 'Baraja default es');
insert into carta values(339, 'default', 'Baraja default es', "Violar a un conocido.");
insert into cartablanca values(339, 'default', 'Baraja default es');
insert into carta values(340, 'default', 'Baraja default es', "Sexo sorpresa.");
insert into cartablanca values(340, 'default', 'Baraja default es');
insert into carta values(341, 'default', 'Baraja default es', "Lanzamiento de enanos.");
insert into cartablanca values(341, 'default', 'Baraja default es');
insert into carta values(342, 'default', 'Baraja default es', "Una lobotomia hecha con un picahielos.");
insert into cartablanca values(342, 'default', 'Baraja default es');
insert into carta values(343, 'default', 'Baraja default es', "La vagina de Pilar Bardem.");
insert into cartablanca values(343, 'default', 'Baraja default es');
insert into carta values(344, 'default', 'Baraja default es', "Ninos con correas.");
insert into cartablanca values(344, 'default', 'Baraja default es');
insert into carta values(345, 'default', 'Baraja default es', "Actitud.");
insert into cartablanca values(345, 'default', 'Baraja default es');
insert into carta values(346, 'default', 'Baraja default es', "Un camello de dibujos animados disfrutando el fresco sabor de un cigarrillo.");
insert into cartablanca values(346, 'default', 'Baraja default es');
insert into carta values(347, 'default', 'Baraja default es', "Acurrucarse con tu pareja.");
insert into cartablanca values(347, 'default', 'Baraja default es');
insert into carta values(348, 'default', 'Baraja default es', "Multiples heridas por apuñalamiento");
insert into cartablanca values(348, 'default', 'Baraja default es');
insert into carta values(349, 'default', 'Baraja default es', "Emborracharse con enjuague bucal.");
insert into cartablanca values(349, 'default', 'Baraja default es');
insert into carta values(350, 'default', 'Baraja default es', "Esnifar pegamento.");
insert into cartablanca values(350, 'default', 'Baraja default es');
insert into carta values(351, 'default', 'Baraja default es', "Hulk Hogan.");
insert into cartablanca values(351, 'default', 'Baraja default es');
insert into carta values(352, 'default', 'Baraja default es', "El gay que aparece en todas las series modernas.");
insert into cartablanca values(352, 'default', 'Baraja default es');
insert into carta values(353, 'default', 'Baraja default es', "Constantino Romero durmiendo en un colchon LoMonaco.");
insert into cartablanca values(353, 'default', 'Baraja default es');
insert into carta values(354, 'default', 'Baraja default es', "Bestialidad.");
insert into cartablanca values(354, 'default', 'Baraja default es');
insert into carta values(355, 'default', 'Baraja default es', "Colegios tradicionalmente negros.");
insert into cartablanca values(355, 'default', 'Baraja default es');
insert into carta values(356, 'default', 'Baraja default es', "Beber solo.");
insert into cartablanca values(356, 'default', 'Baraja default es');
insert into carta values(357, 'default', 'Baraja default es', "Ninos con cancer de culo.");
insert into cartablanca values(357, 'default', 'Baraja default es');
insert into carta values(358, 'default', 'Baraja default es', "Cagar y bautizarlo.");
insert into cartablanca values(358, 'default', 'Baraja default es');
insert into carta values(359, 'default', 'Baraja default es', "Mujeres en anuncios de yogurt.");
insert into cartablanca values(359, 'default', 'Baraja default es');
insert into carta values(360, 'default', 'Baraja default es', "Manos de pianista.");
insert into cartablanca values(360, 'default', 'Baraja default es');
insert into carta values(361, 'default', 'Baraja default es', "Whiskas Premium.");
insert into cartablanca values(361, 'default', 'Baraja default es');
insert into carta values(362, 'default', 'Baraja default es', "Un sorteo de bofetadas.");
insert into cartablanca values(362, 'default', 'Baraja default es');
insert into carta values(363, 'default', 'Baraja default es', "Hacer lo correcto.");
insert into cartablanca values(363, 'default', 'Baraja default es');
insert into carta values(364, 'default', 'Baraja default es', "World of Warcraft.");
insert into cartablanca values(364, 'default', 'Baraja default es');
insert into carta values(365, 'default', 'Baraja default es', "Desayunar con la reina.");
insert into cartablanca values(365, 'default', 'Baraja default es');
insert into carta values(366, 'default', 'Baraja default es', "Ocultar una erecciOn.");
insert into cartablanca values(366, 'default', 'Baraja default es');
insert into carta values(367, 'default', 'Baraja default es', "Mearse un poquito.");
insert into cartablanca values(367, 'default', 'Baraja default es');
insert into carta values(368, 'default', 'Baraja default es', "Cuando te tiras un pedo y te cagas un poquito.");
insert into cartablanca values(368, 'default', 'Baraja default es');
insert into carta values(369, 'default', 'Baraja default es', "Hacer trampas en las Olimpiadas Especiales.");
insert into cartablanca values(369, 'default', 'Baraja default es');
insert into carta values(370, 'default', 'Baraja default es', "La estupidez del ser humano.");
insert into cartablanca values(370, 'default', 'Baraja default es');
insert into carta values(371, 'default', 'Baraja default es', "Desayunar un burrito con olor a culo.");
insert into cartablanca values(371, 'default', 'Baraja default es');
insert into carta values(372, 'default', 'Baraja default es', "Pedos vaginales.");
insert into cartablanca values(372, 'default', 'Baraja default es');
insert into carta values(373, 'default', 'Baraja default es', "Dar el 110%.");
insert into cartablanca values(373, 'default', 'Baraja default es');
insert into carta values(374, 'default', 'Baraja default es', "Robarle la novia a un amigo.");
insert into cartablanca values(374, 'default', 'Baraja default es');
insert into carta values(375, 'default', 'Baraja default es', "Ensenarle a un robot a amar.");
insert into cartablanca values(375, 'default', 'Baraja default es');
insert into carta values(376, 'default', 'Baraja default es', "Re-regalar.");
insert into cartablanca values(376, 'default', 'Baraja default es');
insert into carta values(377, 'default', 'Baraja default es', "Atracar un banco de esperma.");
insert into cartablanca values(377, 'default', 'Baraja default es');
insert into carta values(378, 'default', 'Baraja default es', "Alimentar a Montserrat Caballo.");
insert into cartablanca values(378, 'default', 'Baraja default es');
insert into carta values(379, 'default', 'Baraja default es', "Darse por culo debajo de las sabanas.");
insert into cartablanca values(379, 'default', 'Baraja default es');
insert into carta values(380, 'default', 'Baraja default es', "Un Tamagochi abandonado.");
insert into cartablanca values(380, 'default', 'Baraja default es');
insert into carta values(381, 'default', 'Baraja default es', "Un mongolo musculado.");
insert into cartablanca values(381, 'default', 'Baraja default es');
insert into carta values(382, 'default', 'Baraja default es', "Morir.");
insert into cartablanca values(382, 'default', 'Baraja default es');
insert into carta values(383, 'default', 'Baraja default es', "Comerse las galletas antes de la venta benefica.");
insert into cartablanca values(383, 'default', 'Baraja default es');
insert into carta values(384, 'default', 'Baraja default es', "Comer directamente de la olla.");
insert into cartablanca values(384, 'default', 'Baraja default es');
insert into carta values(385, 'default', 'Baraja default es', "Hacer un reloj de arena.");
insert into cartablanca values(385, 'default', 'Baraja default es');
insert into carta values(386, 'default', 'Baraja default es', "Sexo oral no reciproco.");
insert into cartablanca values(386, 'default', 'Baraja default es');
insert into carta values(387, 'default', 'Baraja default es', "Guinarle el ojo a los viejos.");
insert into cartablanca values(387, 'default', 'Baraja default es');
insert into carta values(388, 'default', 'Baraja default es', "Ligar en la clinica de abortos.");
insert into cartablanca values(388, 'default', 'Baraja default es');
insert into carta values(389, 'default', 'Baraja default es', "Cabrearte tanto que te empalmas.");
insert into cartablanca values(389, 'default', 'Baraja default es');
insert into carta values(390, 'default', 'Baraja default es', "Escuchar atentamente.");
insert into cartablanca values(390, 'default', 'Baraja default es');
insert into carta values(391, 'default', 'Baraja default es', "Bebes muertos.");
insert into cartablanca values(391, 'default', 'Baraja default es');
insert into carta values(392, 'default', 'Baraja default es', "Una carrera de sillas de ruedas hasta la muerte.");
insert into cartablanca values(392, 'default', 'Baraja default es');
insert into carta values(393, 'default', 'Baraja default es', "Un mono fumando un cigarrillo.");
insert into cartablanca values(393, 'default', 'Baraja default es');
insert into carta values(394, 'default', 'Baraja default es', "Demasiada gomina.");
insert into cartablanca values(394, 'default', 'Baraja default es');
insert into carta values(395, 'default', 'Baraja default es', "Un mimo teniendo un ataque al corazon.");
insert into cartablanca values(395, 'default', 'Baraja default es');
insert into carta values(396, 'default', 'Baraja default es', "Pacman comiendo corrida descontrolodamente.");
insert into cartablanca values(396, 'default', 'Baraja default es');
insert into carta values(397, 'default', 'Baraja default es', "Un relato erotico de Harry Potter.");
insert into cartablanca values(397, 'default', 'Baraja default es');
insert into carta values(398, 'default', 'Baraja default es', "Peanut Butter Jelly Time.");
insert into cartablanca values(398, 'default', 'Baraja default es');
insert into carta values(399, 'default', 'Baraja default es', "Kim Jong-il.");
insert into cartablanca values(399, 'default', 'Baraja default es');
insert into carta values(400, 'default', 'Baraja default es', "Un leñador desnudo.");
insert into cartablanca values(400, 'default', 'Baraja default es');
insert into carta values(401, 'default', 'Baraja default es', "Bebo para olvidar ___.");
insert into cartanegra values(401, 'default', 'Baraja default es', 1);
insert into carta values(402, 'default', 'Baraja default es', "___:bueno hasta la ultima gota.");
insert into cartanegra values(402, 'default', 'Baraja default es', 1);
insert into carta values(403, 'default', 'Baraja default es', "Que es ese sonido?");
insert into cartanegra values(403, 'default', 'Baraja default es', 1);
insert into carta values(404, 'default', 'Baraja default es', "A que huele?");
insert into cartanegra values(404, 'default', 'Baraja default es', 1);
insert into carta values(405, 'default', 'Baraja default es', "Durante el sexo, me gusta pensar en ___.");
insert into cartanegra values(405, 'default', 'Baraja default es', 1);
insert into carta values(406, 'default', 'Baraja default es', "La medicina alternativa ahora usa las propiedades curativas de ___.");
insert into cartanegra values(406, 'default', 'Baraja default es', 1);
insert into carta values(407, 'default', 'Baraja default es', "Mientras flipaba con acido ___ se convirtio en ___.");
insert into cartanegra values(407, 'default', 'Baraja default es', 2);
insert into carta values(408, 'default', 'Baraja default es', "Por culpa de un error de marketing El Corte lngles ha dejado de vender ___.");
insert into cartanegra values(408, 'default', 'Baraja default es', 1);
insert into carta values(409, 'default', 'Baraja default es', "Por que estoy pegajoso?");
insert into cartanegra values(409, 'default', 'Baraja default es', 1);
insert into carta values(410, 'default', 'Baraja default es', "Hoy el tio de Bricomania construira ___.");
insert into cartanegra values(410, 'default', 'Baraja default es', 1);
insert into carta values(411, 'default', 'Baraja default es', "Que me traje de Marruecos?");
insert into cartanegra values(411, 'default', 'Baraja default es', 1);
insert into carta values(412, 'default', 'Baraja default es', "Que ayuda a Obama a relajarse?");
insert into cartanegra values(412, 'default', 'Baraja default es', 1);
insert into carta values(413, 'default', 'Baraja default es', "___. Chocala!");
insert into cartanegra values(413, 'default', 'Baraja default es', 1);
insert into carta values(414, 'default', 'Baraja default es', "Durante el comunmente infravalorado Periodo Marron de Picasso, hizo cientos de pinturas de ___.");
insert into cartanegra values(414, 'default', 'Baraja default es', 1);
insert into carta values(415, 'default', 'Baraja default es', "___. Es una trampa!");
insert into cartanegra values(415, 'default', 'Baraja default es', 1);
insert into carta values(416, 'default', 'Baraja default es', "Que es lo que mas le gusta a Aznar?");
insert into cartanegra values(416, 'default', 'Baraja default es', 1);
insert into carta values(417, 'default', 'Baraja default es', "A que no puedes comer solo uno!");
insert into cartanegra values(417, 'default', 'Baraja default es', 1);
insert into carta values(418, 'default', 'Baraja default es', "La guerra sirve para ___.");
insert into cartanegra values(418, 'default', 'Baraja default es', 1);
insert into carta values(419, 'default', 'Baraja default es', "Que es lo que no te gustaria encontrar en un plato de comida china?");
insert into cartanegra values(419, 'default', 'Baraja default es', 1);
insert into carta values(420, 'default', 'Baraja default es', "Cual es el proximo juguete del HappyMeal?");
insert into cartanegra values(420, 'default', 'Baraja default es', 1);
insert into carta values(421, 'default', 'Baraja default es', "Este año, en vez de carbón,Papa Noel traerá ___ a los niños malos.");
insert into cartanegra values(421, 'default', 'Baraja default es', 1);
insert into carta values(422, 'default', 'Baraja default es', "EE.UU. ha empezado a enviar ___ a los niños en Afghanistan.");
insert into cartanegra values(422, 'default', 'Baraja default es', 1);
insert into carta values(423, 'default', 'Baraja default es', "Que toma Vin Diesel para cenar?");
insert into cartanegra values(423, 'default', 'Baraja default es', 1);
insert into carta values(424, 'default', 'Baraja default es', "Qué encontraría tu abuela perturbador pero extrañamente encantador?");
insert into cartanegra values(424, 'default', 'Baraja default es', 1);
insert into carta values(425, 'default', 'Baraja default es', "Cual es mi anti-droga?");
insert into cartanegra values(425, 'default', 'Baraja default es', 1);
insert into carta values(426, 'default', 'Baraja default es', "Cómo mantengo estabale mi relación de pareja?");
insert into cartanegra values(426, 'default', 'Baraja default es', 1);
insert into carta values(427, 'default', 'Baraja default es', "Ojalá no hubiese perdido el manual de ___");
insert into cartanegra values(427, 'default', 'Baraja default es', 1);
insert into carta values(428, 'default', 'Baraja default es', "El paraíso está lleno de ___.");
insert into cartanegra values(428, 'default', 'Baraja default es', 1);
insert into carta values(429, 'default', 'Baraja default es', "En la nueva película original de Disney Channel, Hannah Montana se enfrenta por primera vez con ___");
insert into cartanegra values(429, 'default', 'Baraja default es', 1);
insert into carta values(430, 'default', 'Baraja default es', "La liga de Fútbol ha prohibido ___ por dar a los jugadores una ventaja injusta.");
insert into cartanegra values(430, 'default', 'Baraja default es', 1);
insert into carta values(431, 'default', 'Baraja default es', "Cuando sea Presidente crearé el ministerio de ___");
insert into cartanegra values(431, 'default', 'Baraja default es', 1);
insert into carta values(432, 'default', 'Baraja default es', "Por qué no puedo dormir por las noches?");
insert into cartanegra values(432, 'default', 'Baraja default es', 1);
insert into carta values(433, 'default', 'Baraja default es', "Qué es lo que hay que hacer para llevarte a la cama?");
insert into cartanegra values(433, 'default', 'Baraja default es', 1);
insert into carta values(434, 'default', 'Baraja default es', "Cuál es el vicio secreto de Batman?");
insert into cartanegra values(434, 'default', 'Baraja default es', 1);
insert into carta values(435, 'default', 'Baraja default es', "___? Hay una aplicación para eso!");
insert into cartanegra values(435, 'default', 'Baraja default es', 1);
insert into carta values(436, 'default', 'Baraja default es', "Cuál es mi poder secreto?");
insert into cartanegra values(436, 'default', 'Baraja default es', 1);
insert into carta values(437, 'default', 'Baraja default es', "Cuando esté en la cárcel, meteré ___ de contrabando.");
insert into cartanegra values(437, 'default', 'Baraja default es', 1);
insert into carta values(438, 'default', 'Baraja default es', "Cuando sea millonario, lenvataré una estatua de 20 metros enconmemoración de ___");
insert into cartanegra values(438, 'default', 'Baraja default es', 1);
insert into carta values(439, 'default', 'Baraja default es', "Qué me llevaría en un viaje al pasado para convencer a la gente de que soy un poderoso mago?");
insert into cartanegra values(439, 'default', 'Baraja default es', 1);
insert into carta values(440, 'default', 'Baraja default es', "Qué me produce gases incontrolados?");
insert into cartanegra values(440, 'default', 'Baraja default es', 1);
insert into carta values(441, 'default', 'Baraja default es', "Asi es, yo mate a ___ ,Que como lo hice? ___.");
insert into cartanegra values(441, 'default', 'Baraja default es', 2);
insert into carta values(442, 'default', 'Baraja default es', "Y el premio de la academia por ___ es para ___.");
insert into cartanegra values(442, 'default', 'Baraja default es', 2);
insert into carta values(443, 'default', 'Baraja default es', "En mi proximo truco, sacare ___ de ___.");
insert into cartanegra values(443, 'default', 'Baraja default es', 2);
insert into carta values(444, 'default', 'Baraja default es', "Canal Historia presenta: ___ la historia de ___.");
insert into cartanegra values(444, 'default', 'Baraja default es', 2);
insert into carta values(445, 'default', 'Baraja default es', "Cual es la proxima pareja de superheroes?");
insert into cartanegra values(445, 'default', 'Baraja default es', 2);
insert into carta values(446, 'default', 'Baraja default es', "Haz un haiku.");
insert into cartanegra values(446, 'default', 'Baraja default es', 3);
insert into carta values(447, 'default', 'Baraja default es', "Que es lo mas crujiente?");
insert into cartanegra values(447, 'default', 'Baraja default es', 1);
insert into carta values(448, 'default', 'Baraja default es', "A que huelen las personas mayores?");
insert into cartanegra values(448, 'default', 'Baraja default es', 1);
insert into carta values(449, 'default', 'Baraja default es', "___ probado en niños, aprobado por las madres.");
insert into cartanegra values(449, 'default', 'Baraja default es', 1);
insert into carta values(450, 'default', 'Baraja default es', "Que mejora con los años?");
insert into cartanegra values(450, 'default', 'Baraja default es', 1);
insert into carta values(451, 'default', 'Baraja default es', "Lo siento, acabo de ___.");
insert into cartanegra values(451, 'default', 'Baraja default es', 1);
insert into carta values(452, 'default', 'Baraja default es', "A los blancos les gusta ___.");
insert into cartanegra values(452, 'default', 'Baraja default es', 1);
insert into carta values(453, 'default', 'Baraja default es', "La vida era dificil para los cavernicolas antes de ___.");
insert into cartanegra values(453, 'default', 'Baraja default es', 1);
insert into carta values(454, 'default', 'Baraja default es', "Quien ha robado las galletas del tarro de las galletas?");
insert into cartanegra values(454, 'default', 'Baraja default es', 1);
insert into carta values(455, 'default', 'Baraja default es', "Que es lo mas emo?");
insert into cartanegra values(455, 'default', 'Baraja default es', 1);
insert into carta values(456, 'default', 'Baraja default es', "Antes de matarle,Señor Bond, me gustaria enseñarle ___.");
insert into cartanegra values(456, 'default', 'Baraja default es', 1);
insert into carta values(457, 'default', 'Baraja default es', "La excursion al campo fue completamente arruinada por ___.");
insert into cartanegra values(457, 'default', 'Baraja default es', 1);
insert into carta values(458, 'default', 'Baraja default es', "Que es el mejor amigo de una chica?");
insert into cartanegra values(458, 'default', 'Baraja default es', 1);
insert into carta values(459, 'default', 'Baraja default es', "Los estudios demuestran que las ratas de laboratorio resuelven laberintos un 50% mas rapido tras ser expuestas a ___.");
insert into cartanegra values(459, 'default', 'Baraja default es', 1);
insert into carta values(460, 'default', 'Baraja default es', "Que me han estado ocultando mis padres?");
insert into cartanegra values(460, 'default', 'Baraja default es', 1);
