package com.xokundevs.cchmavenserver.bddconnectivity.model;
// Generated 26-may-2019 19:42:04 by Hibernate Tools 4.3.1


import com.xokundevs.cchmavenserver.bddconnectivity.model.Carta;
import com.xokundevs.cchmavenserver.bddconnectivity.model.Usuario;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Baraja generated by hbm2java
 */
@Entity
@Table(name="baraja"
    ,catalog="cardshumanity"
)
public class Baraja  implements java.io.Serializable {


     private BarajaId id;
     private Usuario usuario;
     private String idioma;
     private Set<Carta> cartas = new HashSet<Carta>(0);

    public Baraja() {
    }

	
    public Baraja(BarajaId id, Usuario usuario) {
        this.id = id;
        this.usuario = usuario;
    }
    public Baraja(BarajaId id, Usuario usuario, String idioma, Set<Carta> cartas) {
       this.id = id;
       this.usuario = usuario;
       this.idioma = idioma;
       this.cartas = cartas;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="emailUsuario", column=@Column(name="emailUsuario", nullable=false, length=50) ), 
        @AttributeOverride(name="nombreBaraja", column=@Column(name="nombreBaraja", nullable=false, length=30) ) } )
    public BarajaId getId() {
        return this.id;
    }
    
    public void setId(BarajaId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="emailUsuario", nullable=false, insertable=false, updatable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="idioma", length=10)
    public String getIdioma() {
        return this.idioma;
    }
    
    public void setIdioma(String idioma) {
        this.idioma = idioma;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="baraja")
    public Set<Carta> getCartas() {
        return this.cartas;
    }
    
    public void setCartas(Set<Carta> cartas) {
        this.cartas = cartas;
    }




}


