package com.xokundevs.cchmavenserver.bddconnectivity.model;
// Generated 10-may-2019 17:18:01 by Hibernate Tools 4.3.1


import com.xokundevs.cchmavenserver.bddconnectivity.model.Usuario;
import java.util.HashSet;
import java.util.Set;

/**
 * Baraja generated by hbm2java
 */
public class Baraja  implements java.io.Serializable {


     private BarajaId id;
     private Usuario usuario;
     private String idioma;
     private Set cartas = new HashSet(0);

    public Baraja() {
    }

	
    public Baraja(BarajaId id, Usuario usuario) {
        this.id = id;
        this.usuario = usuario;
    }
    public Baraja(BarajaId id, Usuario usuario, String idioma, Set cartas) {
       this.id = id;
       this.usuario = usuario;
       this.idioma = idioma;
       this.cartas = cartas;
    }
   
    public BarajaId getId() {
        return this.id;
    }
    
    public void setId(BarajaId id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getIdioma() {
        return this.idioma;
    }
    
    public void setIdioma(String idioma) {
        this.idioma = idioma;
    }
    public Set getCartas() {
        return this.cartas;
    }
    
    public void setCartas(Set cartas) {
        this.cartas = cartas;
    }




}


