package com.xokundevs.cchmavenserver.bddconnectivity.model;
// Generated 10-may-2019 17:18:01 by Hibernate Tools 4.3.1



/**
 * Carta generated by hbm2java
 */
public class Carta  implements java.io.Serializable {


     private CartaId id;
     private Baraja baraja;
     private String texto;
     private Cartablanca cartablanca;
     private Cartanegra cartanegra;

    public Carta() {
    }

	
    public Carta(CartaId id, Baraja baraja) {
        this.id = id;
        this.baraja = baraja;
    }
    public Carta(CartaId id, Baraja baraja, String texto, Cartablanca cartablanca, Cartanegra cartanegra) {
       this.id = id;
       this.baraja = baraja;
       this.texto = texto;
       this.cartablanca = cartablanca;
       this.cartanegra = cartanegra;
    }
   
    public CartaId getId() {
        return this.id;
    }
    
    public void setId(CartaId id) {
        this.id = id;
    }
    public Baraja getBaraja() {
        return this.baraja;
    }
    
    public void setBaraja(Baraja baraja) {
        this.baraja = baraja;
    }
    public String getTexto() {
        return this.texto;
    }
    
    public void setTexto(String texto) {
        this.texto = texto;
    }
    public Cartablanca getCartablanca() {
        return this.cartablanca;
    }
    
    public void setCartablanca(Cartablanca cartablanca) {
        this.cartablanca = cartablanca;
    }
    public Cartanegra getCartanegra() {
        return this.cartanegra;
    }
    
    public void setCartanegra(Cartanegra cartanegra) {
        this.cartanegra = cartanegra;
    }




}


