package com.xokundevs.cchmavenserver.bddconnectivity.model;
// Generated 26-may-2019 19:42:04 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Carta generated by hbm2java
 */
@Entity
@Table(name="carta"
    ,catalog="cardshumanity"
)
public class Carta  implements java.io.Serializable {


     private CartaId id;
     private Baraja baraja;
     private String texto;
     private Cartablanca cartablanca;
     private Cartanegra cartanegra;

    public Carta() {
    }

	
    public Carta(CartaId id, Baraja baraja) {
        this.id = id;
        this.baraja = baraja;
    }
    public Carta(CartaId id, Baraja baraja, String texto, Cartablanca cartablanca, Cartanegra cartanegra) {
       this.id = id;
       this.baraja = baraja;
       this.texto = texto;
       this.cartablanca = cartablanca;
       this.cartanegra = cartanegra;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idCarta", column=@Column(name="idCarta", nullable=false) ), 
        @AttributeOverride(name="emailUsuario", column=@Column(name="emailUsuario", nullable=false, length=50) ), 
        @AttributeOverride(name="nombreBaraja", column=@Column(name="nombreBaraja", nullable=false, length=30) ) } )
    public CartaId getId() {
        return this.id;
    }
    
    public void setId(CartaId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="emailUsuario", referencedColumnName="emailUsuario", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="nombreBaraja", referencedColumnName="nombreBaraja", nullable=false, insertable=false, updatable=false) } )
    public Baraja getBaraja() {
        return this.baraja;
    }
    
    public void setBaraja(Baraja baraja) {
        this.baraja = baraja;
    }

    
    @Column(name="texto", length=200)
    public String getTexto() {
        return this.texto;
    }
    
    public void setTexto(String texto) {
        this.texto = texto;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="carta")
    public Cartablanca getCartablanca() {
        return this.cartablanca;
    }
    
    public void setCartablanca(Cartablanca cartablanca) {
        this.cartablanca = cartablanca;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="carta")
    public Cartanegra getCartanegra() {
        return this.cartanegra;
    }
    
    public void setCartanegra(Cartanegra cartanegra) {
        this.cartanegra = cartanegra;
    }




}


