package com.xokundevs.cchmavenserver.bddconnectivity.model;
// Generated 10-may-2019 17:18:01 by Hibernate Tools 4.3.1



/**
 * CartablancaId generated by hbm2java
 */
public class CartablancaId  implements java.io.Serializable {


     private int idCarta;
     private String emailUsuario;
     private String nombreBaraja;

    public CartablancaId() {
    }

    public CartablancaId(int idCarta, String emailUsuario, String nombreBaraja) {
       this.idCarta = idCarta;
       this.emailUsuario = emailUsuario;
       this.nombreBaraja = nombreBaraja;
    }
   
    public int getIdCarta() {
        return this.idCarta;
    }
    
    public void setIdCarta(int idCarta) {
        this.idCarta = idCarta;
    }
    public String getEmailUsuario() {
        return this.emailUsuario;
    }
    
    public void setEmailUsuario(String emailUsuario) {
        this.emailUsuario = emailUsuario;
    }
    public String getNombreBaraja() {
        return this.nombreBaraja;
    }
    
    public void setNombreBaraja(String nombreBaraja) {
        this.nombreBaraja = nombreBaraja;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CartablancaId) ) return false;
		 CartablancaId castOther = ( CartablancaId ) other; 
         
		 return (this.getIdCarta()==castOther.getIdCarta())
 && ( (this.getEmailUsuario()==castOther.getEmailUsuario()) || ( this.getEmailUsuario()!=null && castOther.getEmailUsuario()!=null && this.getEmailUsuario().equals(castOther.getEmailUsuario()) ) )
 && ( (this.getNombreBaraja()==castOther.getNombreBaraja()) || ( this.getNombreBaraja()!=null && castOther.getNombreBaraja()!=null && this.getNombreBaraja().equals(castOther.getNombreBaraja()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdCarta();
         result = 37 * result + ( getEmailUsuario() == null ? 0 : this.getEmailUsuario().hashCode() );
         result = 37 * result + ( getNombreBaraja() == null ? 0 : this.getNombreBaraja().hashCode() );
         return result;
   }   


}


