package com.xokundevs.cchmavenserver.bddconnectivity.model;
// Generated 10-may-2019 17:18:01 by Hibernate Tools 4.3.1



/**
 * Cartablanca generated by hbm2java
 */
public class Cartablanca  implements java.io.Serializable {


     private CartablancaId id;
     private Carta carta;

    public Cartablanca() {
    }

    public Cartablanca(Carta carta) {
       this.carta = carta;
    }
   
    public CartablancaId getId() {
        return this.id;
    }
    
    public void setId(CartablancaId id) {
        this.id = id;
    }
    public Carta getCarta() {
        return this.carta;
    }
    
    public void setCarta(Carta carta) {
        this.carta = carta;
    }




}


