package com.xokundevs.cchmavenserver.bddconnectivity.model;
// Generated 26-may-2019 19:42:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="cardshumanity"
)
public class Usuario  implements java.io.Serializable {


     private String emailUsuario;
     private String nombreUsuario;
     private String contrasenya;
     private Integer partidasGanadas;
     private String imagenPerfil;
     private Set<Baraja> barajas = new HashSet<Baraja>(0);

    public Usuario() {
    }

	
    public Usuario(String emailUsuario) {
        this.emailUsuario = emailUsuario;
    }
    public Usuario(String emailUsuario, String nombreUsuario, String contrasenya, Integer partidasGanadas, String imagenPerfil, Set<Baraja> barajas) {
       this.emailUsuario = emailUsuario;
       this.nombreUsuario = nombreUsuario;
       this.contrasenya = contrasenya;
       this.partidasGanadas = partidasGanadas;
       this.imagenPerfil = imagenPerfil;
       this.barajas = barajas;
    }
   
     @Id 

    
    @Column(name="emailUsuario", unique=true, nullable=false, length=50)
    public String getEmailUsuario() {
        return this.emailUsuario;
    }
    
    public void setEmailUsuario(String emailUsuario) {
        this.emailUsuario = emailUsuario;
    }

    
    @Column(name="nombreUsuario", length=15)
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }

    
    @Column(name="contrasenya", length=100)
    public String getContrasenya() {
        return this.contrasenya;
    }
    
    public void setContrasenya(String contrasenya) {
        this.contrasenya = contrasenya;
    }

    
    @Column(name="partidasGanadas")
    public Integer getPartidasGanadas() {
        return this.partidasGanadas;
    }
    
    public void setPartidasGanadas(Integer partidasGanadas) {
        this.partidasGanadas = partidasGanadas;
    }


@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set<Baraja> getBarajas() {
        return this.barajas;
    }
    
    public void setBarajas(Set<Baraja> barajas) {
        this.barajas = barajas;
    }




}


