package com.xokundevs.cchmavenserver.bddconnectivity.model;
// Generated 10-may-2019 17:18:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String emailUsuario;
     private String nombreUsuario;
     private String contrasenya;
     private Integer partidasGanadas;
     private String imagenPerfil;
     private Set barajas = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String emailUsuario) {
        this.emailUsuario = emailUsuario;
    }
    public Usuario(String emailUsuario, String nombreUsuario, String contrasenya, Integer partidasGanadas, String imagenPerfil, Set barajas) {
       this.emailUsuario = emailUsuario;
       this.nombreUsuario = nombreUsuario;
       this.contrasenya = contrasenya;
       this.partidasGanadas = partidasGanadas;
       this.imagenPerfil = imagenPerfil;
       this.barajas = barajas;
    }
   
    public String getEmailUsuario() {
        return this.emailUsuario;
    }
    
    public void setEmailUsuario(String emailUsuario) {
        this.emailUsuario = emailUsuario;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getContrasenya() {
        return this.contrasenya;
    }
    
    public void setContrasenya(String contrasenya) {
        this.contrasenya = contrasenya;
    }
    public Integer getPartidasGanadas() {
        return this.partidasGanadas;
    }
    
    public void setPartidasGanadas(Integer partidasGanadas) {
        this.partidasGanadas = partidasGanadas;
    }
    public String getImagenPerfil() {
        return this.imagenPerfil;
    }
    
    public void setImagenPerfil(String imagenPerfil) {
        this.imagenPerfil = imagenPerfil;
    }
    public Set getBarajas() {
        return this.barajas;
    }
    
    public void setBarajas(Set barajas) {
        this.barajas = barajas;
    }




}


